### ISSUE TITLE
Entering the `decimalCharacterAlternative` is not taken into account on Android Chrome

### ISSUE THREAD

**Issue by balek** [autoNumeric/autoNumeric#264]
I've tried to set aDec to `.` and altDec to `,` and vice versa. In both combinations altDec doesn't work. Just Chrome is affected, everything is working fine on Android Browser.

**Comment by BobKnothe** [comment]
The issue is with the Android Chrome and their decision to not support the "keypress" event and character codes which is critical to how autoNumeric functions. 

I (we) are in the initial sets of finding a work around using the "input" event. This may take some time to write and test.

Please be patient.

**Comment by AlexandreBonneau** [comment]
This issue being a duplicate of #206, please consider closing this one and updating the initial one.

**Comment by AlexandreBonneau** [comment]
Using Chrome 55.0.2883.91 under Android, I do experience the `altDec` problem.
Also, issue #206 is different from this one.

**Comment by AlexandreBonneau** [comment]
This is fixed by @BobKnothe work in this [commit](https://github.com/autoNumeric/autoNumeric/commit/5257865155c6e75a8a6f51fbe69ae2ab946a132c). 🎉
