### ISSUE TITLE
Format back to numeric value on POST

### ISSUE THREAD

**Issue by dereuromark** [autoNumeric/autoNumeric#28]
It would be nice if one doesn't have to re-format the posted value after POST to save a valid numeric value. Currently we have to strip out the added currency symbol. We also need to adjust the number (delocalize).

E.g: User input 1.234,56 € is posted exactly as this string.

We need it in 12345.56 (php internal numeric value) for storing again. Or at least in the local format 12.345,56 (which we can than unlocalize on save).

I just assumed this jquery plugin only takes care of a proper input format in regards of display. But unfortunately it also modifies the numeric value accordingly to a non numeric string.

Other similar plugins or HTML5 do that (formatting is only for display to the user).

**Comment by KarugaEdwin** [comment]
Hi @dereuromark was the issue solved been trying to do the same for a couple days, passing a autonumeric value from a value from db

**Comment by gap777** [comment]
I think this issue was the predecessor for the `unformatOnSubmit` option... however, the autonumeric implementation of this feature seems to differ slightly, and significantly, from @LDSign's proposal, which included this:

```
$("input.autoNumeric[value!='']").autoNumeric('reSet');
```

That is, after the form data was generated based on raw values, the input was reset back to the formatted value.

Q: Am I missing something, or is autonumeric unable to unformatOnSubmit *and* reformatAfterSubmit? 

@AlexandreBonneau

**Comment by gap777** [comment]
@AlexandreBonneau

**Comment by AlexandreBonneau** [comment]
Necroing a 10 years old post is not the best solution, specially about a version of AutoNumeric that is not supported anymore for about 7 years.
If you have an issue, please open a new one!
