### ISSUE TITLE
How to format without decimal?

### ISSUE THREAD

**Issue by saiful** [autoNumeric/autoNumeric#35]
Hallo All..

I want to ask how to format number without decimal?

example : 

1,000.00 to be 1,000

thank you for your hands...

**Comment by avalanche1** [comment]
thanks!

**Comment by dario86** [comment]
Thanks ;)

**Comment by vrecalde** [comment]
Thanks!!!!

**Comment by yawshadi** [comment]
Thanks Bob

**Comment by AlexandreBonneau** [comment]
Note ; the way to define the number of decimals has changed since `v4.0.0-beta.22`.

Now, you need to be more explicit about it, by setting the `decimalPlaces` option (cf. the [documentation](https://github.com/autoNumeric/autoNumeric/tree/next#options)).
Moreover, you can now fine grain how many decimal you want for each focused/unfocused state, as well as the precision to keep as the `rawValue`, using `decimalPlacesRawValue`, `decimalPlacesShownOnBlur` and `decimalPlacesShownOnFocus`.

**Comment by namuCnd** [comment]
고마워요 2.0 버젼 못찾아서 헤멤

**Comment by mrskl21** [comment]
thanks
