### ISSUE TITLE
  decimal Separator problem after clicking on the " , " sumbol

### ISSUE THREAD

**Issue by eliematta** [autoNumeric/autoNumeric#420]
@BobKnothe @jarinudom @kossnocorp @CoryFoy @brunowego 
Dears,

when im trying to enter a decimal value after clicking on ","
the value after the above symbol is being erased .

EX: when im trying to enter 1,5, i pressed on 1, then when i enter the 5 the value become 5 and not 1.5.
attached for ur info

Im using the 1.9.44 version .
$('.mobile-autonumeric').autoNumeric('init', {'aSep':" " , 'aDec': ',' ,'mDec': '2'
capture
capture1
});
![capture](https://cloud.githubusercontent.com/assets/10115887/24137828/25fcae56-0e1e-11e7-8245-9bc589ff6eea.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10115887/24137829/2607031a-0e1e-11e7-8f52-2027ddc3b666.PNG)

**Comment by AlexandreBonneau** [comment]
Hi @eliematta, for info, there is no need to close an issue then open a new one if you just want to modify it ; you could have directly edited the [previous one](https://github.com/BobKnothe/autoNumeric/issues/419).

Also please try to not mention all the people that are or used to maintain autoNumeric ; the mainteners are automatically notified ; no need to add some noise!

There, about your issue, I'd suggest using a more recent version since 1.9.44 is very far behind the stable 2.0.10 `master` branch (and the upcoming 4.0.0 very soon).

Finally, a live example (on codepen for instance) will help us help you a lot, thanks.

**Comment by eliematta** [comment]
Dear @AlexandreBonneau 
my apologize for the disturbing, its the first time opening an issue on GitHub.
so all i need is to upgrade to that above version :D

**Comment by BobKnothe** [comment]
Yes please try 2.0.10 and test. If the issue persist let us know otherwise close.

It is also important to let us know the operating system you are using.

thanks

**Comment by AlexandreBonneau** [comment]
*(and the browser and its version, since unfortunately even being in 2017, those still have (quite a lot of) quirks)*

**Comment by eliematta** [comment]
Dears,

Im using android kitkat/im using the library for building mobile apps.
anw i will test and get back to you .

**Comment by BobKnothe** [comment]
Please know that android's stock browser is not fully supported. The underlying issue is that Chrome for android does not key codes and the keypress event which are currently essential  for autoNumeric to function properly.

We are in the early stages of building support for android but it is too early to say when or if it can be done.

**Comment by eliematta** [comment]
Dear BobKnothe,

i have tried the same library with "." as separator and it worked fine. this is for your info.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting your issue @eliematta, but currently with the info you gave us, we do not have enough to try to reproduce, and hence fix your bug.

A codepen would be a must.
Please keep in mind that Android is not fully supported as Robert said though.
