### ISSUE TITLE
Support for smooth entry numbers (decimal delimiter keypress will not be ignored)

### ISSUE THREAD

**Issue by meesha81** [autoNumeric/autoNumeric#431]
Hi, I would like to ask you for this feature, which should improve daily using autoNumeric forms, when input have some default value (eg. `0.000`).
Current behavior prevents inputting number without looking to monitor, because user have to manage default value (rest zero - eq. delete one with Delete).
This issue is based on 4 years experience of hundreds of our users, who daily entered many numbers. Thank you consider this case.

Input field looks like: `|0.000`
I would like to input: `1345.45`
State before decimal delimiter keypressed: `1345|0.000`
Now user keypress decimal delimiter: `1345.|000`
Now user type deicimals `45`: `1345.45|0`

It cause that user can input smoothly number without looking to monitor and using other keys (eg. delete/backspace/arrows).

**Comment by AlexandreBonneau** [comment]
I could see an option `decimalCharacterInputMode` to activate that special behavior when set to `'force'`, while the default would still be `'normal'`.

From the top of my head, this could prove difficult to implement with the potential side effects. We'll take a look when we'll be able, mostly after the `v4` release.

**Comment by AlexandreBonneau** [comment]
@meesha81 In the mean time, you could also just hit `Esc` while you are focusing the input.

This will either cancel any changes made to that input value since the last focus or validation with the 'Enter' key, or if no such change is detected, if will select all the input value, which will then allows you to enter whatever you like without having to check your screen.

To sum up ;
- make sure `selectOnFocus` is set to `true` if you use the tab key to navigate through your autoNumeric-managed elements
- or just hit `Esc` while your element already have the focus.
In both case the whole input content will be selected and you'll be able to enter your numbers.

**Comment by AlexandreBonneau** [comment]
Ok so I'm closing this feature request since you can achieve exactly what you want to do:

- either by using the `caretPositionOnFocus` option set to `decimalLeft`, in combination with `selectOnFocus`:
```js
{
    selectOnFocus: false,
    caretPositionOnFocus: AutoNumeric.options.caretPositionOnFocus.decimalLeft,
}
```
- by just using the default (see my previous comment above):
```js
{
    selectOnFocus: true,
}
```
- or by hitting the `Escape` key (once if you haven't changed the input content, twice if you did change the content)

In the first two cases, your users will be able to start tying their numbers right away without having to check their screen.

You can see that in action in the WIP [documentation](http://autonumeric.org/#/guide).
