### ISSUE TITLE
[Question] Can Colour/Background be changed for the currencySymbol/aSign?

### ISSUE THREAD

**Issue by Zuhayer** [autoNumeric/autoNumeric#437]
Other than the question this Repo is great, it has all the feature I needed. (y) 

I was unable to find reference to colour change in the docs.

**Comment by AlexandreBonneau** [comment]
Hello @Zuhayer, thanks for the greeting!

Unfortunately, as the [doc](https://github.com/autoNumeric/autoNumeric/tree/next#questions) states, in order to keep our issue list clean, *The issue list of this repository is **exclusively** for bug reports and feature requests.*.

If you have a question, come by IRC or our [Gitter channel](https://gitter.im/autoNumeric/autoNumeric) and we'll happily try to help you!

(otherwise, I added a new feature [very recently](https://github.com/autoNumeric/autoNumeric/commit/98ed0d9b62b4f04f3697f811e9bc5a2f54715f63) `styleRules` that will allow you to change the color of the AutoNumeric-managed element as you wish)

**Comment by Zuhayer** [comment]
ok. I will check out styleRules and if I need any guidance I will seek you out on Gitter.
