### ISSUE TITLE
Upgrade Webpack to 3.*

### ISSUE THREAD

**Issue by AlexandreBonneau** [autoNumeric/autoNumeric#438]
The title is explicit ; we should upgrade Webpack from `1.*` to `3.*`.

**Comment by an-kh** [comment]
Greetings!

I am getting an error when I'm trying to import autonumeric (using webpack 2.3.3):
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

Is this error related to the described issue?

**Comment by AlexandreBonneau** [comment]
It's possible ; currently we are using Webpack `1.14.0`.
The switch to Webpack `2.*` has been postponed for the next `4.1.0` (while `4.0.0` should be out at the end of this week, normally).

If you are a webpack master, feel free to create a PR to help us switching (and if it works before the end of the week, then it'll be part of the next stable `4.0.0`! :D

**Comment by an-kh** [comment]
Thank you for the reply.
Sorry, I'm not a webpack expert, so I don't this I'm the best suited for the task. Only the day before have seen the features of the library and wanted to try them out it in the project environment.

Btw the error
![2](https://cloud.githubusercontent.com/assets/26059661/26575290/08714a48-453e-11e7-8848-8416f5ae7f1c.jpg)
appears here
![1](https://cloud.githubusercontent.com/assets/26059661/26575240/d7899b74-453d-11e7-86e5-8bcae5a425af.jpg)
Maybe you'll find this info useful.

**Comment by AlexandreBonneau** [comment]
Quick question @an-kh ; do you see the same error when you try to import AutoNumeric with webpack `1.*` ?

I'm asking because the `module.exports = AutoNumeric;` line has been around for some time now, and I'm wondering if it's really a webpack `2.*` related problem there.

**Comment by an-kh** [comment]
I'll try to check that. Don't know if work project is going to build if I straitforward downgrade webpack to the previous version, so, otherwise may try to make sample.

**Comment by tomasz** [comment]
This issue is somewhat explained in https://github.com/webpack/webpack/issues/4039. Specifically this comment from webpack's author https://github.com/webpack/webpack/issues/4039#issuecomment-273804003 states that ES6's `import` statements and ComonJS's `module.exports` assignments cannot be mixed. After some recent changes, `module.exports` has value `undefined` and is read-only when it comes to webpack.

A quick and dirty workaround is to remove `modules: false` option from the babel presets in the dependent project's config. **BUT** this change disables the tree-shaking offered by webpack 2, so not a great solution.

Something like this should do the trick.
```javascript
// src/main.js
export { default } from './AutoNumeric';
export { default as AutoNumeric } from './AutoNumeric';
export { default as AutoNumericEvents } from './AutoNumericEvents';
export { default as AutoNumericOptions } from './AutoNumericOptions';
export { default as AutoNumericDefaultSettings } from './AutoNumericDefaultSettings';
export { default as AutoNumericPredefinedOptions } from './AutoNumericPredefinedOptions';
```

Will try to make a pull request with the migration to webpack 2, but no promises. 😉

**Comment by AlexandreBonneau** [comment]
This is great, thank you for those precious info!

By the way, `v4` is being delayed for the time being (vacations + working on complex rewrites will not help speed things up ;)), so you have some time to try to create a PR if you want :)

Thanks again!
