### ISSUE TITLE
Workaround setSelectionRange in android

### ISSUE THREAD

**Issue by funny-falcon** [autoNumeric/autoNumeric#439]
https://issuetracker.google.com/issues/36926301#comment6

**Comment by AlexandreBonneau** [comment]
Hey Sokolov, thanks for linking this here. It's good to know a workaround exists.

On the other hand it seems Robert somehow managed to fix that already since his [last commits](https://github.com/autoNumeric/autoNumeric/commit/b6dada9e4d38bd20c557aeca95e5763c2e8e8339) add support for Chrome, and I do not remember seeing the jumping-caret problem you described in 2011. So that's good news!

I'll close this issue for the time being since the bug has been addressed already, but thank you again for linking this here.

Feel free to re-open it if you feel I missed something here!

Cheers
