### ISSUE TITLE
Add a new `'null'` options to the `emptyInputBehavior` setting

### ISSUE THREAD

**Issue by Gle2nn** [autoNumeric/autoNumeric#447]
### Expected behavior
Allow null values to be used with AutoNumeric.

### Actual behavior
Null values are currently ignored.

### Steps to reproduce the problem
See issue #446. 

### Proposal (from @AlexandreBonneau ):

- Implement a change to `emptyInputBehavior` to allow null.
- Do a better job of handling null/undefined if the new option is not used: log a warning to the console, throw an error, or silently treat them as an empty string.

**Comment by AlexandreBonneau** [comment]
As written in issue #446 [comment](https://github.com/autoNumeric/autoNumeric/issues/446#issuecomment-301359905), this commit implements:
- `emptyInputBehavior` now accepts the `'null'` option, which allow to use `anElement.set(null)` and change the `rawValue` to `null` when the autoNumeric element is emptied, and
- Instead of silently dismissing `undefined` and `null` when used with `set()`, a warning is shown in the console for both cases.
