### ISSUE TITLE
When searching for the parent form element, the tagName can be undefined

### ISSUE THREAD

**Issue by bforsythe** [autoNumeric/autoNumeric#448]
Backstory:  I'm trying to update from autoNumeric 1.7.1 to 2.0.12.  We use knockout.js.  When opening an edit modal, we create our markup in javascript (using a ko template), and then call applyBindings to it before the markup is inserted into the DOM.  This worked in 1.7.1.

With 2.0.12, it's blowing up in the `form()` method:
```js
form() {
	if (this.domElement.tagName.toLowerCase() === 'body') {
            return null;
        }

        let node = this.domElement;
        let tagName;
        do {
            node = node.parentNode;
            if (AutoNumericHelper.isNull(node)) {
                // Special case when using templates with frameworks like Vue.js, where the input element can be 'detached' when initializing the DOM structure
                return null;
            }

            tagName = node.tagName.toLowerCase();

            if (tagName === 'body') {
                break;
            }
        } while (tagName !== 'form');

        if (tagName === 'form') {
            return node;
        } else {
            return null;
        }
    }
```
the final `node` is a document-fragment and and its tagName is naturally undefined, and `Cannot read property 'toLowerCase' of undefined` results.

Trivial example of issue: 
`      var input = $('<input type="text" />');
      new AutoNumeric(input[0], AutoNumeric.getPredefinedOptions().NorthAmerican);`

Is there some way around this/something I'm missing?  Thanks for your time, big fan of the updates in 2.0.12 so I'd really like to upgrade if it's possible.
Thanks, Brandon

**Comment by bforsythe** [comment]
It's worth mentioning that replacing:
`tagName = node.tagName.toLowerCase();`
with:
`tagName = node.tagName ? node.tagName.toLowerCase() : ''`
Does seem to work-- I'd still appreciate some input however, as a general rule I'm fairly hesitant to fork something like this without having a better understanding of the rest of the library.

**Comment by AlexandreBonneau** [comment]
Hey @bforsythe, thanks for you input on that.

First things first, `v4` will be here very, very soon (in a few days normally), perhaps if you are currently upgrading your (very) old autoNumeric version, you could give the current `next` branch a try?

It's named as `beta`, but we strive to only commit 100% tested and working code in it so it's pretty stable :)

That said, you would be safe doing:
```js
tagName = node.tagName ? node.tagName.toLowerCase() : '';
```
since currently we call `this.form()` every time you try to access the parent form element.

On the other hand, we started using the `this.parentForm` attribute in order to prevent having to search for the parent `<form>` element each time a `form*` function is called.

I could see modifying that `form()` method to retrieve that if it exists.

**Comment by AlexandreBonneau** [comment]
This is now fixed in `next`.
@bforsythe could you please check that it does fix your problem?
If not, feel free to reopen this issue!

**Comment by bforsythe** [comment]
Thanks for the quick response!  v4.0.0-beta.18 fixes the issue, appreciate it.  During some testing I did find and open #449 BTW
