### ISSUE TITLE
Unformatter doesn't respect decimalCharacter setting

### ISSUE THREAD

**Issue by wc-matteo** [autoNumeric/autoNumeric#458]
### Expected behavior
Unformatting values doesn't change the decimalCharacter

### Actual behavior
Unformatting values changes the decimalCharacter

### Steps to reproduce the problem
1. Using autoNumeric `4.0.0-beta.20` and the browser `Chrome` version `58` on `Windows`,
2. I used the options `{ unformatOnHover: true, decimalCharacter: ',', digitGroupSeparator: '.' }`, and 
3. Initialized my AutoNumeric object with the call `  AutoNumeric.multiple('input', options)`,
4. Triggering the unformatter (in this case with alt, on hover) changes the decimalCharacter to '.'

### CodePen
https://codepen.io/anon/pen/ZyQXNr

**Comment by AlexandreBonneau** [comment]
Yes, this is by design, as the option name suggest, it unformats the formatted element value when hovering it with the mouse and using the `Alt` key.
Unformatting there means that it removes any non-number characters and show the *raw* value, as understood by Javascript (ie. `12.34` is a valid number, while `12,34` is not).

I updated the comment in `AutoNumericOptions.js` so that it'll be picked up in the future documentation.

**Comment by AlexandreBonneau** [comment]
By the way, if you want to remove the digit group separators (on focus), you can use the `noSeparatorOnFocus` option.

**Comment by wc-matteo** [comment]
Now I get it. A Javascript number is the base and formatting is applied to it or removed from it.

For my case, I wanted to remove formatting on submit (hover was just for demonstration purposes). My backend (asp.net core mvc) expects a number with a `decimalCharacter` according to the visitor's language preference. So I cannot _always_ send a Javascript number.
