### ISSUE TITLE
Allow the positive & negative signs to be specified via options

### ISSUE THREAD

**Issue by Gle2nn** [autoNumeric/autoNumeric#478]
### Expected behavior
I would like to be able to format a positive number with a trailing sign that is equal to `&nbsp;`. For example, `'1.234.56&nbsp;'`.
It does not appear possible to override the characters used for `+` and `-`.

### Actual behavior
I can format a negative value with trailing sign: `1,234.56-`
I can format a positive value with trailing sign: `1.234.56+`

Using `&nbsp;` will allow proper alignment of columns of numeric data with trailing signs (in tables, with monospaced fonts, likely other provisos).

**Comment by AlexandreBonneau** [comment]
For this to work, we need to validate the characters used so that there are no overlapping between the digit separator, the positive/negative signs, the decimal character, the decimal character alternative and finally the suffix text.

**Comment by AlexandreBonneau** [comment]
The options will be named `negativeSignCharacter` and `positiveSignCharacter`, respectively.

In order to simplify entering the negative sign, while it could be set to (almost) any non-number character, the only way to change the positive or negative state of the element would still be to use the hyphen key (`'-'`), not the key defined as the `negativeSignCharacter`.

For instance, using the option:
```js
const anElement = new AutoNumeric(input, { negativeSignCharacter: 'z' });
```
a negative value would be displayed `z42.00` (instead of the default `-42.00`), but entering the `'z'` key will *not* modify `z42.00` into `42.00`.

**Comment by AlexandreBonneau** [comment]
This issue is a pure hell 🔥 of side effects on side effects, on side effects :/

Changing such a key element so close to the AutoNumeric core is a pain, specially since the `'-'` character is the negative sign for non-formatted values, and a lot of assumptions were made in the code between the raw value and the formatted one.
Juggling between those two values and the `-` character assumptions in all the test cases is a *huge* headache 😱.

The feature implementation is *finished*, but as soon as I create a new test case, I discover some new corner cases. So it's coming soon™.

I fear some of those corner cases will escape the unit and end-to-end cases written so far.
Please, test that new feature thoroughly in `v4.1.0-beta.2`!

😅

**Comment by AlexandreBonneau** [comment]
Note: the negative and positive sign characters cannot be equal to each other, and cannot be part of the digit group separator, the decimal character, the decimal character alternative, the brackets and the suffix text.
Moreover, they can only be a string of `length` 1.
