### ISSUE TITLE
input type = number throws exception

### ISSUE THREAD

**Issue by bindrid** [autoNumeric/autoNumeric#487]
### Expected behavior
I was expecting <input type='number'> (html5) to behave like <input type='text'>

### Actual behavior
AutoNumeric threw and exceptionL SCRIPT5022: The input type "number" is not supported by autoNumeric

### Steps to reproduce the problem
In IE 11: 
HTML:
            <input type="number" class="form-control" maxlength="3"  title="Area Code" data-bind="textInput:AreaCode">

JavaScript:

          new AutoNumeric( $div.find("input[type='number']:first")[0], AutoNumeric.getPredefinedOptions().integerPos);

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
http://jsbin.com/yezaqak/58/edit

Thanks for reporting a bug or giving us great ideas with your feature request!

**Comment by AlexandreBonneau** [comment]
Hey @bindrid, this is not a bug and a limitation on how browsers work. It's detailled in the documentation [here](https://github.com/autoNumeric/autoNumeric#on-input-elements) : *"Note : the number type is **not** supported simply because autoNumeric formats numbers as strings (ie. `'123.456.789,00 &#8364;'`) that this input type does not allow."*

To sum up, when you use `type="number"`, the browser only accepts numbers, and no characters/string, hence AutoNumeric cannot modify the element text correctly.

**Comment by AlexandreBonneau** [comment]
Also, you do not need to first select the element with jQuery to pass it to AutoNumeric, the library is clever enough to find and select it for you!

There, FTFY : http://jsbin.com/teyukiweni/edit?html,js,output ;)

**Comment by bindrid** [comment]
Thanks for the prompt reply and the advice. My bad for missing it in the documentation :( 
My actual code lives inside a knockout binding handler callback function

**Comment by AlexandreBonneau** [comment]
No problem ;)
