### ISSUE TITLE
Full keyboard on mobile

### ISSUE THREAD

**Issue by nilskp** [autoNumeric/autoNumeric#499]
### Expected behavior
Just found this library and first thing I noticed was that on mobile (or specifically Chrome on Android) that the numeric keyboard is not used, which I was expecting from a numerically focused library.

### Actual behavior
Full alphabetic keyboard.

### Steps to reproduce the problem
Should be obvious.

**Comment by AlexandreBonneau** [comment]
Hello @nilskp, 

"This not a bug, it's a feature"™ ;P

As you can see in the [documentation](https://github.com/autoNumeric/autoNumeric/tree/next#on-input-elements), due to browser constraints, the input type `number` is not supported.
This is because when using that input type, the browsers will refuse any non-numeric characters (like spaces, currency symbol and the like) and treat the input content as a number instead of a string.

If you want a numeric keyboard to appear when using AutoNumeric, you can however use the input type `tel` which is supported:
```html
<input type='tel' value="1234.56">
```
That will solve your problem.

We thought about programmatically changing the input type to `tel` by default, but since the dev is *(supposed to be)* aware about the different input types available, we decided it was not our place to change the source Html.

If you have any other question, feel free to ask!

**Comment by nilskp** [comment]
@AlexandreBonneau I was actually thinking of `inputmode="numeric"`, but that may have similar limitations?

**Comment by AlexandreBonneau** [comment]
You could use that too yes, but English is not the only target of this library and some other languages could need to access specific characters or symbols.
I'm pretty sure if we were to modify the Html, this could prevent those languages to be properly managed.

We'll let the dev handle that on their own. However, thanks for putting your finger on that potential issue ; I'll update the documentation to mention the Html `inputmode` attribute, thanks!
