### ISSUE TITLE
Bug with `minimumValue` setting of '0.01'

### ISSUE THREAD

**Issue by tomdaniel0x01** [autoNumeric/autoNumeric#501]
### Expected behavior
I should be able to type '0.01' into the input field

### Actual behavior
I cannot type '0.01' into the input field. However, I can type '1.01' and then replace the first '1' with a '0'.

### Steps to reproduce the problem
1. Using autoNumeric `<v4.0.3>` and the browser `Chrome` version `<60.0.3112.113>` on `OSX 10.12.6 (16G29)`,
2. I used the options
```
var autoNumericOptions = {
                maximumValue    : '999999999.99',
                minimumValue    : '0.01',
            };
```
, and
3. Initialized my AutoNumeric object with the call `anElement = new AutoNumeric('#amount').northAmerican(autoNumericOptions);`,

**Comment by AlexandreBonneau** [comment]
Since the lowest accepted number you set is higher than zero, it means than when you start typing, if you try to enter 0, then it's refused since this value is out of the accepted limits.
This behavior is normal.

If you want to enter the lowest value, I'd suggest setting it as the initial value. Or you can use the mouse wheel down to set it.

Not including 0 in the accepted range will always pose problem when trying to clear the input. Could you change that on your end? What are you trying to achieve?

**Comment by tomdaniel0x01** [comment]
I understand that in terms of simplicity this is an acceptable behavior, but a `minimumValue` of anything between 1 > 0 does not represent the intended behavior of `minimumValue` because the a range of values can't actually be entered by the user down to the minimum value. My use case represents monetary values as an amount for a bill and an input of zero is unacceptable. There are some use cases where incrementing from a starting value is also not acceptable to the end user experience.

Perhaps there can be a timeout period, say 3 or so seconds, where '0.0' can be accepted. Once the timeout is completed, then the field would erase all zero input. This would give the user a chance to actually enter something less than 1.

For now my work around will be just set `minimumValue` to 0 and manually reject 0 as a valid input after submission.

**Comment by AlexandreBonneau** [comment]
I understand this is not an ideal situation (not being able to temporarily erase the content of the input).
I'm not keen on using timeouts since I would forecast quite a lot edge cases there that could bite us back.

Perhaps another solution would be to add a new option `overrideZeroLimitation` (or something equivalent) set to `false` by default, and that would allow a user to input `0` in the element, whatever the limits, and would then revert to the last good known value on blur if it's still equal to `0`.

What do you think about that?

**Comment by tomdaniel0x01** [comment]
I think this sounds like a reasonable solution without adding too many complications. Thanks for your attentiveness!

**Comment by AlexandreBonneau** [comment]
Followup on issue #543
