### ISSUE TITLE
Pasting values in a `readOnly` element should not be possible

### ISSUE THREAD

**Issue by renandegrandi** [autoNumeric/autoNumeric#505]
### Expected behavior
When you have an input [disabled = disabled], the input can not be changed, but if the user types the value (ctrl + c | ctrl + v), the value changes.

### Actual behavior
As the field is disabled the user could not change its value using (ctrl + c | ctrl + v)

### Steps to reproduce the problem
1. Using autoNumeric `2.0.13` and the browser `<Chrome>`.

### Obs:
I checked that the event (paste) is added by calling the onPaste function.
This function is not validated at any time if the field is disabled or not.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this, will fix that asap!

**Comment by AlexandreBonneau** [comment]
This is fixed in `v4.1.0-beta.10`!

**Comment by renandegrandi** [comment]
@AlexandreBonneau  

This solution will not work for when we disable a field according to some rule or when the field is not just (readOnly).
for example when we use $ (element) .prop ('disabled', true).

Could you make this change in version 2.0.13?

**Comment by AlexandreBonneau** [comment]
Disabled and read-only input element have different behaviors.
Mainly the read-only element can be focused and have their value sent when the form is submitted.
On the other hand disabled input cannot be focused and are not sent with the form submit.
So your last request is out of the scope of this issue.

I guess we could add a new `disabled` option that would set the `disabled` attribute on load on the input element.
However since AutoNumeric allows to be used on `contenteditable` elements, we would have to add some validation rules to check if the user is trying to set that `disabled` option on a non-input tag.

Could you please perhaps create an issue about that new option if you want to see that happen? Thanks.

About preventing the addition of the `paste` event handler, that's indeed preferred, but then we'd need to make sure to recreate that handler if the user update the settings by setting the `readOnly` option to `false`.

Lastly, `v2.0.13` uses the old code base, with the `holder` object and jQuery dependency, and is not supported anymore.
A **lot** of improvements have been made since last year, please upgrade to the stable branch (currently `v4.0.3`).
