### ISSUE TITLE
Setting the input `value` directly with Javascript without using the `set()` method is not supported

### ISSUE THREAD

**Issue by fugafree** [autoNumeric/autoNumeric#513]
### Expected behavior
To be able to fill an input field's value with jQuery's val function.

### Actual behavior
Sadly, it does not work with AutoNumeric 4. And I can not call any trigger on the field to store (or even just parse) the value which was loaded to the input by the val function.
I have several AutoNumeric fields and it would be a huge (and risky) work to refactor all value set from this:
```
$('#autonumeric_field1').val('60100').trigger('blur');
```
to this:
```
AutoNumeric.getAutoNumericElement($('#autonumeric_field1').get(0)).set(60100);
```
The first one was worked with AutoNumeric 1.9.

The main problem isn't that it not formatting the value anymore but it doesn't even store the value. If I set it with jQuery's val, then I move the cursor to the field and move it out, the AutoNumeric restore the previous value to the field. It is a very, very dangerous behavior. The user can belive that the new value will be submitted but it isn't if the AutoNumeric restore its value.

### Steps to reproduce the problem
1. Using autoNumeric `4.0.3` and the browser `Chrome` version `61.0.3163.100 (Official Build) (64-bit)` on `Windows 10`,
2. Set the field's value with jQuery's val function
3. Move the cursor above the field then move it out.

### Link to live example
[JSFiddle](https://jsfiddle.net/L3pbbbLs/1/)

**Comment by AlexandreBonneau** [comment]
Hi @fugafree , since the jQuery dependency has been dropped in `v3.0.0-beta.3`, you can no longer rely on jQuery to update the input value as before unfortunately.

Do note that if you use pure JS to set the AutoNumeric element directly like this:
```js
 let an = AutoNumeric.getAutoNumericElement(document.getElementById('issue_455'));
 an.node().value = 45433;
```
it won't work either.

AutoNumeric do not add watches to the input `value` attribute and hence as you pointed out, the only *right* way to set a value for an AutoNumeric element once it has already been initialized is to use the `set()` method `aNElement.set(60100)`, or in your case if you do not have a reference to the AutoNumeric object previously created:
```js
AutoNumeric.getAutoNumericElement(document.getElementById('autonumeric_field1')).set(60100);
```

So far we chose to ignore external changes since the user could modify the input value with anything he wants (a character string for instance), breaking the formatting, the different variable states and plenty of other info we store for each AutoNumeric object.

From the top of my head, we *could* possibly add some 'watchers' on the `value` property like this:
```js
Object.defineProperty(an.node(), 'value', {
    set: val => {
        console.log('value has changed', val); //DEBUG
        an.set(val);
    },
});
```
...but we would need to check for all possible side effects, and make sure it also works for `contenteditable` elements and the other html tags.
Then we would also need to write the related unit and end-to-end tests.
A PR could be a good start for testing that :)


*By the way I think I should allow users to directly call `AutoNumeric.getAutoNumericElement('#autonumeric_field1')` without having to first find the DOM element. This would be more consistent with the other functions*

**Comment by fugafree** [comment]
Quick and detailed answer, thank you! I like both of your idea,
* it would be good to watch the value change because without that the mentioned silent error could happen and
* the getAutoNumericElement function could be very useful.

By the way I use external ("non user") changes a lot: calculating sum of fields and fill that to a readonly AutoNumeric field.

Maybe a static set function could be also useful:
`AutoNumeric.setAutoNumericElement('#autonumeric_field1', 4010)`.
Which would only the short version/alias of
`AutoNumeric.getAutoNumericElement('#autonumeric_field1').set(4010)`.

**Comment by AlexandreBonneau** [comment]
For info you can now use:
```js
AutoNumeric.getAutoNumericElement('#theInput');
```
directly without having to first select the DOM element. This has been fixed in #514.

**Comment by fugafree** [comment]
Wow! That was fast. Thanks!

**Comment by AlexandreBonneau** [comment]
For info, static `set()` and `get*()` functions are now available in `v4.1.0-beta.12`.

**Comment by VoimiX** [comment]
The problem could be easily solved by overriding jquery val() function like this

```
var originalVal = this.originalVal = $.fn.val;
    $.fn.val = function (value) {
        if (typeof value == 'undefined') {
            if ($(this).attr('data-money')) { //your condition to determine if it is autonumeric control
                return stepup.forms.getCurVal($(this));              
            }
            return originalVal.call(this);
        }
        else {
            if ($(this).attr('data-money')) {
                return stepup.forms.setCurVal($(this), value);                
            }
            return originalVal.call(this, value);
        }
    };

stepup.forms = {
 setCurVal: function (jquerySelector, value) {
        var domElement = $(jquerySelector).get(0);
        if (domElement == null) {
            alert('element by "' + jquerySelector + '" is not found');
            return;
        }

        var autoNum = AutoNumeric.getAutoNumericElement(domElement);
        if (autoNum == null) {
            alert('autoNumeric object "' + jquerySelector + '" is not found or properly initialized');
            return;
        }
        autoNum.set(value);
    },

    getCurVal: function (jquerySelector) {
        var domElement = $(jquerySelector).get(0);
        if (domElement == null) {
            alert('element by "' + jquerySelector + '" is not found');
            return;
        }

        if (domElement.value == "") return "";

        var autoNum = AutoNumeric.getAutoNumericElement(domElement);
        if (autoNum == null) {
            alert('autoNumeric object "' + jquerySelector + '" is not found or properly initialized');
            return;
        }

        return parseFloat(autoNum.get()).toFixed(2);
    }
}

```

**Comment by AlexandreBonneau** [comment]
The fix for that issue using `Object.defineProperty()` is in the work, but so far PhantomJS is buggy and prevent the tests to be run correctly (see the [PhantomJS issue](https://github.com/ariya/phantomjs/issues/13895).

We won't be able to close our issue if PhantomJS cannot fix their issue first :/

**Comment by AlexandreBonneau** [comment]
AutoNumeric now listens to any external changes made to `input.value`.
This is available in `v4.1.0-beta.15`.

Caveat: For now, AutoNumeric cannot listen to external changes made to `textContent` (ie. non-`<input>` elements)

**Comment by AlexandreBonneau** [comment]
Also note that the unit tests for this feature are [written](https://github.com/autoNumeric/autoNumeric/blob/97da1727c3ba865da4fd76f87050bd02cfd9b82d/test/unit/autoNumeric.spec.js#L3713) and working for Firefox and Chrome, but that PhantomJS has an upstream bug that make those fail.

Hence, those tests will be deactivated until that [PhantomJS bug](https://github.com/ariya/phantomjs/issues/13895) is resolved upstream.

**Comment by feanor07** [comment]
I am using `v4.1.0-beta.20` and setting `input.value` does not seem to be working. it is doing the exact same thing mentioned in the initial description.

**Comment by AlexandreBonneau** [comment]
For info, in order for AutoNumeric to watch for external change, you need to explicitly set the `watchExternalChanges` option to `true` (this is `false` by default).
