### ISSUE TITLE
Left and right wheel throw Error!

### ISSUE THREAD

**Issue by jdanilow** [autoNumeric/autoNumeric#519]
### Expected behavior
catch left and right wheel event and do nothing

### Steps to reproduce the problem
1. Focus input with autonumeric initialized,
2. Move the mouse wheel left or right.

**Comment by AlexandreBonneau** [comment]
Hey @jdanilow, thanks for reporting this.

However since I do not have a mouse that allow such things, could you post more detailled basic info about the problem?

For instance:
- what's the error message?
- a link to a reproducible example
- which version of AN? (please follow the issue template)
- what `key` and `keyCode` are sent when you use the wheel left/right?

**Comment by AlexandreBonneau** [comment]
I'll close this for now.
Feel free to reopen this issue with more info.
