### ISSUE TITLE
Use passive event listeners

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#523]
### Expected behavior
No warnings in normal AutoNumeric operation

### Actual behavior
In Chrome with "Verbose" logging turned on, we get warnings similar to:

```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

### Steps to reproduce the problem
1. Using autoNumeric `4.1.0-beta.12` and the browser `Chrome` version `62.0.3202.62 64-bit` on `Windows 10`,
2. I used the options 

```
{
    currencySymbol : ' €',
    decimalCharacter : ',',
    digitGroupSeparator : '.',
}
```

3. Initialized my AutoNumeric object with the call

```
new AutoNumeric('#input', {
    currencySymbol : ' €',
    decimalCharacter : ',',
    digitGroupSeparator : '.',
});
```

4. Warning appears

### Link to live example
http://autonumeric.org

### Resources describing the problem
https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive
https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners
https://developers.google.com/web/updates/2016/06/passive-event-listeners

**Comment by AlexandreBonneau** [comment]
The MDN documentation says:

> passive: A Boolean indicating that the listener will never call preventDefault(). If it does, the user agent should ignore it and generate a console warning. See Improving scrolling performance with passive listeners to learn more.

and to describe it more precisely, in the links you provided it says:
> **Passive event listeners** are a new feature in the DOM spec that enable developers to opt-in to better scroll performance by eliminating the need for scrolling to block on touch and wheel event listeners. Developers can annotate touch and wheel listeners with {passive: true} to indicate that they will never invoke preventDefault.

This means that if we were to set `{ passive: true }` on the `wheel` event handler, we would not be able to call `event.preventDefault` anymore, which would break how we manage the `wheel` event.

I would prefer the browser to not output warning messages like this, but unfortunately we cannot do anything about it ; I haven't found any way to prevent the browser to display such message in *Verbose* mode, so for the time being there is no fix for this.

The *good* point is that it's more a notice than a warning, since the `wheel` event handle is clearly not the core of AutoNumeric!

**Comment by alexturpin** [comment]
Fair enough! Hopefully browser vendors provide a way to suppress these one day.

**Comment by wijzijnweb** [comment]
Sorry to reopen this old ticket, but since this is a won't fix can we at least initiate the event if modifyValueOnWheel is true?

After 5 years the warning is still showing and I don't think the browser will remove this since it's a valid warning.

I have create a pull request for this:
https://github.com/wijzijnweb/autoNumeric/pull/1
