### ISSUE TITLE
Webpack usage / Big file size

### ISSUE THREAD

**Issue by LDSign** [autoNumeric/autoNumeric#529]
Hi

I am using webpack to integrate autoNumeric like so:

import AutoNumeric from 'autonumeric';

So far it works...but the file size is very big including autonumeric. It seems "dist/autoNumeric.js" will be used and the part after "sourceMappingURL" will not be removed.

So, what is the prober way to integrate autoNumeric with Webpack?

Thanks,
Frank

**Comment by AlexandreBonneau** [comment]
Hey @LDSign, when you are using:
```js
import AutoNumeric from 'autonumeric';
```
Webpack looks at the 'main' file declared in `package.json` and import the already compiled `dist/autoNumeric.js` file.

So, instead of importing the default generated file, since you are importing the class from a script, you should import the *source* file `../node_modules/autonumeric/src/main.js` (I need to rewrite [that documentation part](https://github.com/autoNumeric/autoNumeric/tree/next#in-another-script) to make it more clear ;)).

Since you'll directly import the non-compiled source, Webpack should then be able to correctly bundle it.

Tell us if it worked!

**Comment by AlexandreBonneau** [comment]
I'll close this for now.
If that did not solve your problem, feel free to reopen it!

**Comment by akarelas-pt** [comment]
Is that how we should import all npm modules in our webpack projects?

ie should we write: `import AutoNumeric from 'autonumeric/src/main.js'` instead of `import AutoNumeric from 'autonumeric'`? If not, then why is there a difference in the usage between AutoNumeric and the other npm modules? Thanks.

**Comment by akarelas-pt** [comment]
@AlexandreBonneau ^^

**Comment by AlexandreBonneau** [comment]
Solved in #561
