### ISSUE TITLE
dictate or on demand format input field

### ISSUE THREAD

**Issue by janokary** [autoNumeric/autoNumeric#532]
When input value is set by javascript and not by entering the value in the input field, how can I format the input?

I now get the number without formating by autoNumeric.

**Comment by AlexandreBonneau** [comment]
Hey @janokary , for any questions, you should join the gitter or IRC channel, not use those issues!

Otherwise, make sure to use the latest AutoNumeric version ; a [new feature](https://github.com/autoNumeric/autoNumeric/issues/513) was recently added so external changes of an input value will now be caught by the AutoNumeric object.
So basically you have nothing special to do to have your input formatted.

With previous version of AutoNumeric, directly setting the input value would bypass any checks by AN, so the *right* way to do it would be to use `set()` like:
```js
aNElement.set(42);
```
