### ISSUE TITLE
Prevent entering any decimal character when only positive numbers are accepted

### ISSUE THREAD

**Issue by Norcoen** [autoNumeric/autoNumeric#535]
### Expected behavior
Input 123,456 results in 123456

### Actual behavior
Input 123,456 results in 12356

### Steps to reproduce the problem
Use autoNumeric with predefined integerPos option or similar settings

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/ptz5kfjm/

**Comment by AlexandreBonneau** [comment]
Preventing the next input here is not the problem ; since AutoNumeric only accept positive integer, it prevent you from entering a float (`123,4` in this case).
So this is normal behavior.

However, for a better user experience, neither the `decimalCharacter` nor the `decimalCharacterAlternative` should be accepted when only integers are accepted.

**Comment by AlexandreBonneau** [comment]
This is fixed in `v4.2.0`
