### ISSUE TITLE
APEX don't see the function

### ISSUE THREAD

**Issue by trudneva** [autoNumeric/autoNumeric#538]
### Expected behavior
APEX recognize autonumeric function

### Actual behavior
APEX doesn't see autonumeric function 

### Steps to reproduce the problem
1. Using autoNumeric last version from gitHub, and the browser `Chrome` version ` 62.0.3202.94` on `Windows 8`,
2. Initialized my AutoNumeric object with the call: My JavaScript code is in Global Page, in PageLoad Dynamic action:
```js
$('.number_field').autoNumeric('init', {
    digitGroupSeparator:'.',
    decimalCharacter:',',
    decimalCharacterAlternative:'.'
});
```

4. When calling the function in runtime I get an error: "Uncaught TypeError: $(...).autoNumeric is not a function".

I tried to put autoNumeric.min.js on the server, also in Static application files and in Statis Workspace files. But nothing worked.

**Comment by AlexandreBonneau** [comment]
Could you please create a reproducible example?

You say `Using autoNumeric last version from gitHub`, but you are using the old jQuery `$('.number_field').autoNumeric('init', options)` way of initializing an AutoNumeric element, a way that has been deprecated for a year now.

So which is which? ;)

**Comment by AlexandreBonneau** [comment]
If you want to [initialize a single element](https://github.com/autoNumeric/autoNumeric/tree/next#initialize-one-autonumeric-object), use:
```js
new AutoNumeric('.number_field', {
    digitGroupSeparator:'.',
    decimalCharacter:',',
    decimalCharacterAlternative:'.'
});
```

If you want to [initialize multiple elements](https://github.com/autoNumeric/autoNumeric/tree/next#initialize-multiple-autonumeric-objects-at-once), use:
```js
AutoNumeric.multiple('.number_field', {
    digitGroupSeparator:'.',
    decimalCharacter:',',
    decimalCharacterAlternative:'.'
});
```

Otherwise, just take a quick look at the *first* paragraph of the documentation and everything is written in it!
