### ISSUE TITLE
Setting the input `value` directly with Javascript without using the `set()` method is still not supported

### ISSUE THREAD

**Issue by feanor07** [autoNumeric/autoNumeric#546]
### Expected behavior
This is a re-openning of [issue-513](https://github.com/autoNumeric/autoNumeric/issues/513); but for `4.1.0-beta.20`. As explained within that issue's solution; AutoNumeric now listens to any external changes made to `input.value` since `v4.1.0-beta.15`; so setting `input.value` should have updated AutoNumeric smoothly.

### Actual behavior
Sadly; the solution mentioned in  [issue-513](https://github.com/autoNumeric/autoNumeric/issues/513) is not working. The same problem mentioned in that specific issue:

> The main problem isn't that it not formatting the value anymore but it doesn't even store the value. If I set it with jQuery's val, then I move the cursor to the field and move it out, the AutoNumeric restore the previous value to the field. It is a very, very dangerous behavior. The user can belive that the new value will be submitted but it isn't if the AutoNumeric restore its value.

is reoccurring with following code snippet.

`$('#autonumeric_field1')[0].value = '60100';`

However; the other solution mentioned;

`AutoNumeric.getAutoNumericElement($('#autonumeric_field1').get(0)).set(98009);`

is working smoothly.

### Steps to reproduce the problem
1. Using autoNumeric `4.1.0-beta.20` and the browser `Chrome` version `63.0.3239.132 (Official Build) (64-bit)` on `Windows 10`,
2. Set the field's value with jQuery's val function
3. Move the cursor above the field then move it out.

### Link to live example
[JSFiddle](https://jsfiddle.net/feanor07/uzn2xa08/2/)

**Comment by AlexandreBonneau** [comment]
`v4.1.0-beta.19` introduced a new `watchExternalChanges` option, set to `false` by default, that allows the AutoNumeric-managed element to watch for external changes.
This default behavior has been set to `false` since in some cases it breaks the integration of AutoNumeric with third-party frameworks (ie. Vue).

You can check the working version of your reproducible code on [codepen](https://codepen.io/AnotherLinuxUser/pen/baJQLB).

*Also, do note that you do not need to first select your element with jQuery before passing it to AutoNumeric. You can just do `new AutoNumeric('#autonumeric_field1', yourOptions)`.*

**Comment by feanor07** [comment]
Thanks for great explanation; sorry I missed that part mentioned in release notes: [v4.1.0-beta.19](https://github.com/autoNumeric/autoNumeric/releases/tag/v4.1.0-beta.19)

**Comment by AlexandreBonneau** [comment]
No problem, the documentation, while up to date, is pretty long and needs to be broken down in a nicely-looking website.
It'll be done *one day* on [the official website](http://autonumeric.org)..
