### ISSUE TITLE
Can't type/edit the input with minimumValue and maximumValue

### ISSUE THREAD

**Issue by brunorios1** [autoNumeric/autoNumeric#560]
### Current behavior
Can't enter value/type on input with defined minimumValue and maximumValue.

### Expected behavior
I expect to enter new values, between min and max values, while I type.

### Steps to reproduce the problem
1. Use autoNumeric version 4.1.0
2. In the browser `<Chrome|Firefox>` 
3. On the `<Linux>` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
var test = new AutoNumeric('.test', {
  minimumValue: '12000',
  maximumValue: '100000',
});
```

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/9gftgqxL/7/

**Comment by AlexandreBonneau** [comment]
This is working as intended; In your particular case, if you put the caret there `120|00`, then type the number `1`, the result would be `120100`, which is more that your defined `maximumValue` of '100000`.
This is why this get dropped.

If you first select the part you want to edit using `120|0|0`, the enter `8`, you correctly get `12080`.

Setting min and max values always have drawbacks, specially if you set a `minimumValue` higher than zero since it means you won't be able to clear the input (see this [feature request](https://github.com/autoNumeric/autoNumeric/issues/543)).

**Comment by brunorios1** [comment]
But if I clear the field using backspace I just can't type anything.

**Comment by AlexandreBonneau** [comment]
Same thing; if you type `1`, it's outside the given limits.

This is also why it won't let you use delete or backspace to clear that field (how are you seeing that? Because it's a bug if it does let your clear the field, and on your jsfiddle it works as expected).

**Comment by AlexandreBonneau** [comment]
@marco2250 please be more specific when saying:

> When I try to input the field, it does not let me to insert anything.

Where did you put the caret/selection, and which key did you type?

**Comment by marco2250** [comment]
First off, I LOVE this component and I've been using it for many years now, since from this page:
http://www.decorplanit.com/plugin/

🥇 

BUT...

Please, try the jsfiddle again, as I removed the default value...
https://jsfiddle.net/marco2250/mo68czk4/2/

I put the focus in the input text field, and it does not let me to input any number.

**Comment by AlexandreBonneau** [comment]
Thanks for the medal ;)

About your inability to enter any character when the input is empty; this is the normal behavior, check my [previous comment](https://github.com/autoNumeric/autoNumeric/issues/560#issuecomment-369729769).

What is happening here is that you are trying to type '1', for instance, which is out of the limit boundary you set.
The only way to add a number in your constrained limits, would be to paste a number between `12000` and `100000`, ie. `22022`.
