### ISSUE TITLE
allowDecimalPadding set to 'false' with decimalPlaces together cause warning to allowDecimalPadding and decimalPlaces together cause warning

### ISSUE THREAD

**Issue by cyberm1nd** [autoNumeric/autoNumeric#592]
In this case getting this one warning:
Warning: Setting 'allowDecimalPadding' to [false] will override the current 'decimalPlaces*' settings [10, 10 and 10].
But it works together just fine. Remove warning pls, cuz it is obsolete.

**Comment by AlexandreBonneau** [comment]
Right now, if you do not want to show the warnings, you can use `showWarnings : false`.

This warning is not obsolete and used for instance when a `decimalPlacesShownOnFocus` is set, and `allowDecimalPadding`set to `false` override that former option.

**Comment by SomeoneIsWorking** [comment]
This makes no sense, `allowDecimalPadding: false` and `decimalPlaces: 5` (for example) works as intended for me yet I get a warning.

> This warning is not obsolete and used for instance when a `decimalPlacesShownOnFocus` is set, and `allowDecimalPadding` set to false override that former option.

Then it should warn if `decimalPlacesShownOnFocus` is set and `allowDecimalPadding` set to false combined not when `allowDecimalPadding` set to false and `decimalPlaces: 5` (for example) combined

**Comment by Blackbaud-MaryRudisill** [comment]
If someone else happens upon this, I was able to get rid of the warnings by setting different properties.
I want a percentage input with no decimals at all, and it turns out allowDecimalPadding was not even needed. The following worked without any warning showing in DevTools.

The asterisk in 'decimalPlaces*' in the warning message was important. It meant that the properties to look at were "decimalPlacesRawValue", "decimalPlacesShownOnBlur", and "decimalPlacesShownOnFocus", not the "decimalPlaces" that I kept focusing on when I first saw the message.

```
  protected autonumericOptions: AutoNumeric.Options = {
    decimalPlaces: 0,
    decimalPlacesRawValue: null,
    decimalPlacesShownOnBlur: null,
    decimalPlacesShownOnFocus: null,
    suffixText: '%',
  };
```
UPDATE:
Well then. Adding on a partial never mind since I am hitting the exact same issue as the others now. 

- I want the user to be able to enter some decimal places (in another control). 
- I do Not want the decimal places to appear by default. 
- If the user enters them then show the numbers, but if not, I do not want zeros to appear. 

So set `decimalPlaces` to 4 to allow the user to enter decimals and set `allowDecimalPadding` to false so that it does not force the user to look at zeros. The control is working Exactly how I want it to, but I still have this warning showing up. I guess I am using the `showWarnings: false` option so this doesn't add to the noise in DevTools.

**Comment by mrfarmer777** [comment]
@AlexandreBonneau,
I'm also using this combination of parameters (`allowDecimalPadding: false` and `decimalPlaces: 3`) to achieve my desired behavior: allowing up to 3 decimal places to be entered, do not pad with zeros when fewer than three are provided. 

It seems, from this thread, like there is some call for this use case to work without warnings. Any way we can configure Autonumeric to ignore or prevent this specific warning as opposed to all of warnings at least?
