### ISSUE TITLE
Numpad decimal separator does not work on IE11 with a keyboard whose numpad decimal key outputs a comma

### ISSUE THREAD

**Issue by McNetic** [autoNumeric/autoNumeric#602]
### Current behavior
The numpad decimal separator on german keyboards produces a `,` (comma). When setting `decimalCharacter` to `,` (comma) and `digitGroupSeparator` to `.` (dot), the numpad decimal separator on a german keyboard is not recognized as `,` (comma) in IE11 (although it produces a `,` (comma) `event.char`) and thus not allowed as input. It works flawless in current versions of Firefox and Chrome.

It also works when setting `decimalCharacterAlternative` to `.` (dot), however, that should not be necessary as per documentation.

### Expected behavior
The numpad decimal separator should be accepted as `,` (comma).

### Steps to reproduce the problem
1. Use autoNumeric version `4.4.0`
2. In the browser `Internet Explorer` version `11`
3. On the `Windows` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, {digitGroupSeparator: '.', decimalCharacter: ','});
```
5. Numad decimal character on german keyboard can not be entered.

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
The issue is reproducible on the autonumeric home page (http://autonumeric.org/) when scrolling down to the example and selecting the third example provided (the separate examples page can not be used in IE11 either, but that's a different problem)

**Comment by McNetic** [comment]
The pull request should fix the issue in IE11. I'm not 100% sure about implications for other browsers.

**Comment by AlexandreBonneau** [comment]
Hey @McNetic, thanks for reporting this.
Sorry it takes some time to get back to you on this, but testing any windows-only bug is a bit of a pain here, since I'm using VMs to do so.

This issue is reminding me of #401 where we found out that in the old IE11 browser, the numpad dot key was outputting..a `Delete` character.
On your end, the numpad is outputting a comma right? What happens if you switch your input language to English?

As you mentioned in your PR, we need to check how this change could affect other platforms.

**Comment by McNetic** [comment]
When using english as input language, the event.key is still `Decimal` while the event.char changes from ',' (comma) to '.' (dot).

**Comment by McNetic** [comment]
When using english as input language, the event.key is still `Decimal` while the event.char changes from ',' (comma) to '.' (dot).

**Comment by McNetic** [comment]
Any news on this one?

**Comment by sbusch** [comment]
We're having this problem with IE11 and German keyboard layout, too.

@AlexandreBonneau all modern browsers should send the correctly localized string as `event.key`, e.g. `.` for English and `,` for German keyboards. I verified this with the evergreen browsers Safari, Chrome (incl. Canary), Firefox (incl. Developer Edition) and Edge (RIP). https://jsfiddle.net/5Ln4g0pj/

IMO the only non-modern browser to be supported by autoNumeric is IE11, and that one sends `Decimal` as `event.key`. @McNetic's PR #603 only applies for that case. Since `event.char` is also a proprietary IE property, is see no problem for that patch: if `char` is missing, the patch is inactive and old logic applies.

According to my understanding, the patch would only break browsers that send `Decimal` as `event.key` AND add the IE-proprietary `event.char` BUT with different values for `event.char` than IE. I this is quite unlikely.

**Comment by AlexandreBonneau** [comment]
Using your jsfiddle, when I use my numpad `.` key, I get `[NumpadDecimal Delete #46 undefined]`.
This is under Firefox `67.0b13`, with the `us_intl` keyboard layout (and a Dvorak keyboard).
Under Chromium `73`, I get `[NumpadDecimal  #46 undefined]`.

I checked under Firefox, Chromium, Firefox for android and Chrome for android, and will take your words for Safari and Edge, and indeed `event.char` is `undefined` for those main browsers.

I'll merge @McNetic PR, thank you both for your researches!
