### ISSUE TITLE
Internet Explorer 11 built-in 'delete input content' action is not picked up by AutoNumeric

### ISSUE THREAD

**Issue by miankulov-modus** [autoNumeric/autoNumeric#615]
### Current behavior
If I enter a value on an input and press X to delete the value it does clear the input, but if I click out of the input (blur) the value in the input is set back instead of clearing the input,

DEMO VIDEO: https://screencast.com/t/4DsqHplkYx

### Expected behavior
DEMO VIDEO: https://screencast.com/t/4DsqHplkYx
Once "X" is pressed the input should remain clear.

### Steps to reproduce the problem
1. Use autoNumeric version `4.1`

Any solution to this?

**Comment by AlexandreBonneau** [comment]
Could you please try with the latest version and see if you still experience your bug?

**Comment by miankulov-modus** [comment]
@AlexandreBonneau I have tried with 4.2.0
<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.2.0"></script>

And yes I still get the same issue, after clicking X and focus out the value is set back on the input

**Comment by miankulov-modus** [comment]
![teest](https://user-images.githubusercontent.com/31111974/47457015-a83bc100-d7de-11e8-9e9c-ccb24c608297.gif)

@AlexandreBonneau  I have added a GIF instead of the video, yes the default "X" from Internet Explorer can you provide a "hacky" way for this? because without the library it's working fine so definitely the library is doing something in order to set the value back.

Thanks,

**Comment by miankulov-modus** [comment]
@AlexandreBonneau, To be honest, I don't know what event it is, or I couldn't find one, but it looks like there isn't a specific event: https://stackoverflow.com/questions/14498396/event-fired-when-clearing-text-input-on-ie10-with-clear-icon

**Comment by AlexandreBonneau** [comment]
Could you try adding the following event listener to see if something is dispatched by IE11?
```js
yourDomElement.addEventListener('input', () => {
    console.log(`Input event is detected`); //DEBUG
});
```

**Comment by miankulov-modus** [comment]
![event](https://user-images.githubusercontent.com/31111974/47483091-1022f380-d841-11e8-9f16-3f89f4b60a64.gif)
@AlexandreBonneau Yes, the input event get's triggered

**Comment by miankulov-modus** [comment]
@AlexandreBonneau  I have tried to reset the input/clear it but I think I need to clear some library-specific data if you can give me a suggestion.

```
    $('input[type="text"].autoNumericFormatting').on('input', function () {
       if ($(this).val() === '') {
           //Need a way to reset library stored value
           $(this).val(''); //doesn't work
       }
    });
```

**Comment by AlexandreBonneau** [comment]
If you want a quick and *hacky* fix, you can listen to the input event and use `clear()` to..clear the input value.
*Note: I'd recommend dropping jQuery since it's known to mess up AutoNumeric and other libraries, and is now pretty much [irrelevant](http://youmightnotneedjquery.com/). Nowadays, vanilla js is just as good if not better anyway.*

So, the hack:
```js
const anElements = AutoNumeric.multiple('input[type="text"].autoNumericFormatting');
anElements.forEach(an => {
    const domNode = an.node();
    domNode.addEventListener('input', () => {
        if (domNode.value === '') {
            an.clear();
        }
    });
});
```

I'll see how I can support that IE11 feature in the next version though, if you are patient enough ;)

**Comment by miankulov-modus** [comment]
@AlexandreBonneau thanks, I will watch for the next release.

Thanks for the amazing support.

**Comment by miankulov-modus** [comment]
@AlexandreBonneau does 4.1 work on IE10? I have tried but it's not formatting the numbers it shows 12345 on IE11 works well

**Comment by miankulov-modus** [comment]
Just in case 4.1 doesn't work with IE10 do you have a separate fix only for the "delete" button this is why the update was done to 4.1 but if it's not working with IE10 will have to stick with 4.0 but also fix the "delete" button issue because deleting with backspace works

**Comment by AlexandreBonneau** [comment]
We indeed need to have a clear 'browser support' chapter in the documentation.
There is an [on going issue](https://github.com/autoNumeric/autoNumeric/issues/539) about that, and I must say I haven't had the time to verify all the browsers in VM (I don't have nor use Windows).

If somebody could try and report their findings, that would be a great start.
Ideally we would want to automate the tests so that we could have an up-to-date support list. But [that too](https://github.com/autoNumeric/autoNumeric/issues/435) needs some more attention :sweat_smile:

**Comment by AlexandreBonneau** [comment]
@miankulov-modus Could you please try the AutoNumeric version on [that branch](https://github.com/autoNumeric/autoNumeric/tree/autoNumeric-615) and see if it fixed your issue? Thanks!

As a reminder, you'd need to build the library using the [following instructions](https://github.com/autoNumeric/autoNumeric/#how-to-contribute), but instead of using the `next` branch, use the `autoNumeric-615` one:
```sh
git clone -b next https://github.com/autoNumeric/autoNumeric.git && cd autoNumeric && yarn && yarn build
```

**Comment by AlexandreBonneau** [comment]
@miankulov-modus You can access all generated files using the unpkg CDN for instance.
When we push a tag, that version is automatically built and made available on jsdelivr and unpkg.

So, when you type unpkg.com/autonumeric in your browser, it automatically selects for you the latest AutoNumeric minified version (ie. https://unpkg.com/autonumeric@4.5.1/dist/autoNumeric.min.js), but you can select whatever version you want, and access whatever file, like the unminified one:
https://unpkg.com/autonumeric@4.5.1/dist/autoNumeric.js

Do note that IE10 is not supported by AutoNumeric *(we use `Map` and `WeakMap`)*.

May I close that issue regarding the IE11 close button?

**Comment by miankulov-modus** [comment]
@AlexandreBonneau  Yes can be closed, I found the problem but don't have a fix for it yet, it's the same as here https://github.com/autoNumeric/autoNumeric/issues/537
