### ISSUE TITLE
float on input elements treated as integer

### ISSUE THREAD

**Issue by dbrw** [autoNumeric/autoNumeric#618]
### Current behavior
When I init AutoNumeric from existing input with float value like `<input value="2000.00">`, AutoNumeric will treat this as integer. We obviously don't want this to happend, because when it generate the unformatted value, it will generate `2000` instead of the original value of `2000.00`.

### Expected behavior
`<input value="2000.00">` should be unformatted as `2000.00`

### Steps to reproduce the problem
1. Use autoNumeric version `4.1.0v`
2. In the browser `,Firefox` version `63.0.3`
3. On the `Linux` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric('input', {decimalCharacter: ',', digitGroupSeparator: '.'})
```
5. Then my computer exploded, for real :-).

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://codepen.io/anon/pen/JeqZwJ?editors=1011

[EDIT]
I think this issue related to #492

**Comment by AlexandreBonneau** [comment]
This is the intended behavior, based on the codepen you provided.

What happens here is that:
1. AutoNumeric parse the html `value`, which is stored as a Javascript number, so `2000`
2. When you use `getNumber()`, you get a **Javascript number**, so `2000`.

Currently and if I'm not mistaken, there is no direct way to retrieve the *string* `'2000.00'` using a `get*()` method. (Although you *could* use `getFormatted(callbackThatRemovesThedigitGroupSeparator)`).
Why? Because `getNumber()` returns `Number(value)`, which will **always** be an integer (try `Number(2000.00)` in your console).

If you were to provide a codepen with what you are trying to achieve, perhaps we could provide more meaningful help.

For info, an extract from the source:
> Developers should use one of the more explicit function names to get what they want :
> - a numeric string : `getNumericString()`
> - a formatted string : `getFormatted()`
> - a number : `getNumber()`, or
> - a localized numeric string : `getLocalized()`

**Comment by dbrw** [comment]
Thank you for fast response, what I am trying to do is like bellow:

- I stored money as double in backend (not the best thing obviously), 
- I want to make user able to change the value of the money using their respective language,
- after some changes, in back-end I want to diff the old value and new value sent by html,
- since the newly posted value always integer, the logic will always think that the value changed, even though in reality it didn't.

It will be very helpful to give me a direction to get the original double number as it was. I think this better be handled in both client and server side.

**Comment by AlexandreBonneau** [comment]
@dbrw indeed, you can use `AutoNumeric.getFormatted(domElement, callback);` to call a custom callback function (see that [documentation part](https://github.com/autoNumeric/autoNumeric#static-methods).

However this looks like an XY problem.

If you have a decimal variable on your back-end, then retrieve a value from your front-end, then just cast both variable to double and compare that, and you'll be good to go.

**Comment by dbrw** [comment]
Great!
Thank you for the great support!
