### ISSUE TITLE
In the environment of ie11 under win10, the cursor moves forward automatically

### ISSUE THREAD

**Issue by smile-xhm** [autoNumeric/autoNumeric#625]
**Steps to reproduce the problem**

1. autoNumeric  v2.0.13
2. In the environment of ie11 under win10,Switch the input method of the system to Chinese
3. Input number, cursor automatically move forward irregularly

**issue:**
1.  In the environment of ie11 under win10, the cursor will move forward automatically when the amount of money is input by the Chinese input method.
2. Is v4.5.3 really incompatible with IE10 and below?

**Comment by AlexandreBonneau** [comment]
> Is v4.5.3 really incompatible with IE10 and below?
Not by itself. To support IE10 and below, you would need some polyfills.

About the erratic cursor movement, could you be more precise? How to do input number when writing in Chinese? Do you have to compose them?

**Comment by smile-xhm** [comment]
**condition to reproduce the problem**

1. windows10 system
2. In IE or edge browser
3. the built-in Chinese input method of windows10

**Details**
In IE or edge browser, I use the built-in input method of windows10 and enter the number in English, the number is displayed in turn, switch to Chinese to continue input, the number can not continue to display sequentially.

**Comment by AlexandreBonneau** [comment]
So if I understand correctly, when switching to `en`, the numbers are correctly entered, but as soon as you switch to the `cn` locale and input method (which I guess includes compositing?), then...what's happening exactly? Is the caret moving forward 2 characters, 3, back?

Since I'm not using windows *(and fear to switch my system to Chinese without being able to switch it back to French)*, I'll unfortunately have a hard time debugging the issue you are describing.
It would be great if you could check which events are sent each time you press a key while having the Chinese input method activated.

For info currently AutoNumeric listens to `keydown`, `keypress` (this will be phased out at one point), and `keyup`. However if you're using IME, could you please check and listen to `compositionStart` and `compositionEnd`, and paste the result here?

If I had a log of each key you pressed alongside the input value and the events sent, then I think I would be able to pin-point what's wrong and how to fix that.

Thanks!

**Comment by smile-xhm** [comment]
Yes,the caret moving forward 2 characters, 3 or 1. And it can be reproduced under the Apple notebook's Safari browser.
of course, I will track the events sent each time I press a key.But I am worried that I can't give you the log you want.
Could you find the Chinese in your IME language options and switch to it ? If it possible, please try to switch the language option of your input method (not the system language) to reproduce the problem, thank you!

**Comment by chaoge7624** [comment]
I have the same problem? Do you got a solution？

**Comment by AlexandreBonneau** [comment]
Well, a log of the events would be a good start to investigate the problem!

**Comment by melloware** [comment]
@AlexandreBonneau you can close this one too since you just removed IE11 support!

**Comment by AlexandreBonneau** [comment]
Indeed, closing since support has been dropped in `4.10.0`.
