### ISSUE TITLE
Console error when using CDN link

### ISSUE THREAD

**Issue by scorsy63** [autoNumeric/autoNumeric#631]
I'm getting this error message in console:

> Source map error: request failed with status 404
Resource URL: https://cdn.jsdelivr.net/npm/autonumeric@4.1.0
Source Map URL: autoNumeric.min.js.map[Learn More]

I've tried using both of these CDN links in my header.  I receive the same error message on both links.

<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.1.0"></script>
<br/>
<script src="https://unpkg.com/autonumeric"></script>
<br/><br/>
Is this error message normal?  Is there a way to prevent the message from showing?

**Comment by AlexandreBonneau** [comment]
I indeed see that source map error with the jsdelivr.net CDN for the previous `4.1.0` version, however I do not see that error with the latest `4.5.4` (using `https://cdn.jsdelivr.net/npm/autonumeric@4.5.4`).

I do not see the error either using `https://unpkg.com/autonumeric`.

See my [test case](https://codepen.io/AnotherLinuxUser/pen/OdzomO).

Perhaps the `v4.1.0` push to jsdelivr was erroneous, hence I would suggest using the latest version of AutoNumeric if you can.

Since there isn't much I can do to fix an already published version on that CDN, I'll close this issue.
Feel free to reopen it if you think we missed something.

**Comment by scorsy63** [comment]
I changed the version from 4.1.0 to 4.5.4 and it's working correctly now, no error message.

I copied that link from the "How to use" section in the Table of Contents.  Didn't know I was using a old version.

Thanks.

**Comment by AlexandreBonneau** [comment]
@scorsy63 thanks for reporting this, I'll update the readme accordingly :)
