### ISSUE TITLE
The selector did not select any valid DOM element. Please check on which element you called AutoNumeric.

### ISSUE THREAD

**Issue by bocanhcam** [autoNumeric/autoNumeric#633]
### Steps to reproduce the problem
1. Use autoNumeric version 4.5.4
2. In the browser <Chrome>
3. On the `<MacOs>` operating system

Sorry for this. This is my first time using this package.

I have this error. `The selector 'money' did not select any valid DOM element. Please check on which element you called AutoNumeric`.

My code is very basic.

`<input type="text" class="money" id="money">
`
`  import AutoNumeric from 'autonumeric';
`
`  const aNElement = new AutoNumeric.multiple('.money');
`

if I change it like this

`  const aNElement = new AutoNumeric.multiple(document.getElementById("money"));
`

I got this error.

`At least one valid parameter is needed in order to initialize an AutoNumeric object
`
And I'm using it inside a component of Vue.js if that's a problem

**Comment by AlexandreBonneau** [comment]
Well first, there is no need to do `AutoNumeric.multiple(document.getElementById("money"))` since you are asking AutoNumeric to initialize multiple elements, while `getElementById` always returns maximum one element.
Instead you should use `const aNElement = new AutoNumeric('#money');` if you are going that road.

I'm guessing `new AutoNumeric.multiple('.money');` works as intended and return an array of AutoNumeric elements for each `.money` element, is that correct?

Regarding your error, I'm 99.99% sure that it comes from the fact that at least one valid parameter is needed in order to initialize an AutoNumeric object, and hence `document.getElementById("money")` does not return an element, but surely `null`. Can you check that ?

Could you please create a [reproducible test case](https://codepen.io/pen/) so we can analyse that report?

**Comment by bocanhcam** [comment]
Thanks for your reply @AlexandreBonneau 

I don't know why but it will only work if I put the script after Vue app in my App.js.

It will not work if I put it on the Component or event the HTML.

You can check this [demo](https://jsfiddle.net/3Lhsxtb6/2/)

**Comment by AlexandreBonneau** [comment]
Well, on the very first line you call `anElement = new AutoNumeric('#money');`, but there are not `#money` element in your html at that point!
You therefore cannot initialize a non-existing element.

If you are using AutoNumeric + vue, I'd recommend the [official vue-autonumeric](https://github.com/autoNumeric/vue-autoNumeric) plugin we created.
