### ISSUE TITLE
Initialisation through data attributes

### ISSUE THREAD

**Issue by marcvangend** [autoNumeric/autoNumeric#637]
Thanks for sharing this library!

When reading "each input can be configured by either setting the options as HTML5 data attributes" in the documentation, I assumed that I could initialise AutoNumeric on an element without writing a single line of JS. 

### Current behavior
As far as I can see, you must initialise AutoNumeric on an input element using JS: `new AutoNumeric('#my-input');`. Then you can use data attributes to set options: `<input type='text' id="my-input" data-decimal-places="0"></input>`.

### Expected behavior
I expected to be able to initialise AutoNumeric through data atrtibutes alone, either with an explicit attribute (eg. `data-autonumeric="enable"`) or implicitly by adding supported attributes like `data-decimal-places="0"`. These expectations were wrong, or the documentation lacks instructions on how to do it.

If it is indeed not possible to initialise AN with data attributes, you may consider this a feature request.

**Comment by AlexandreBonneau** [comment]
Hi @marcvangend, and thank for your input.

*each input can be configured by either setting the options as HTML5 data attributes* means you can just run `new AutoNumeric.multiple('.myAnElements')`, and each of those elements will by initialized with the html5 data attributes you defined, without having to specifically pass the correct options to any specific elements.

As you mentioned, AutoNumeric does not automatically parse the whole page looking for elements that could need to be initialized, and so far I wouldn't want it to, since it could be a pretty big performance issue. Also, this would have to listen to any change to the DOM tree to check if a new elements needs to be initialized.

I do not think this should be done, considering the performance issue mentioned above, and the fact that you can initialize all your elements with a single line of code `new AutoNumeric.multiple('.myAnElements')`.

I'm closing this issue for now.
If more people are interested with such behavior, perhaps I'll reconsider. Sorry.
