### ISSUE TITLE
Input gets multiplied if autoNumeric is called multiple times on the same input

### ISSUE THREAD

**Issue by TempleClause** [autoNumeric/autoNumeric#640]
### Current behavior
When you press the add button x times and go to the first input field and type a number, the number will be inserted x times. 

### Expected behavior
The typed number should only be inserted once.

### Steps to reproduce the problem
Press add link three times and time a number into the first field. 

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://codepen.io/TempleClause/pen/NVqdwK

**Comment by AlexandreBonneau** [comment]
This happens because you are using the `AutoNumeric.multiple()` method to initialize your `.decimalNumber` elements globally.

In the console you can see the warning: `"Warning: A reference to the DOM element you just initialized already exists in the global AutoNumeric element list. Please make sure to not initialize the same DOM element multiple times."`.
Currently we do not prevent initializing the same element multiple times, and display a warning instead.

I guess we *could* change that behavior and check if an element is already initialized as an AutoNumeric objet.
If that's the case, then we would have to choose between ignoring that new initialization, or update the options/value passed as arguments.

I'm not sure how that change would affect existing code that use the current behavior.

**Comment by AlexandreBonneau** [comment]
Since nobody pitched in on that matter, I'll close it for now and keep the current behavior.
If somebody have a voice about that, feel free to post it here.

**Comment by benmehlman** [comment]
I had this same problem.  I would prefer that some more logical behavior be added.. either replace AutoNumeric with new (my preferred behavior), or ignore any duplicates subsequent to the first.  Meanwhile, in my code I use AutoNumeric.getNumericElement() to check for previous initialization.  Here's my code in which I implemented an observer to add AutoNumeric to any existing elements with "money" or "money negative" class.. and to listen for any new input elements added via ajax...

`moneymask_observer = null;
function use_moneymask(parent = null) {
    var parent = parent || $('body');

    function add_moneymasks(parent) {
        parent.find('input.money:not([type=number])').each(function (i, obj) {
            if(AutoNumeric.getAutoNumericElement(obj))
                return;
            var options = { maximumValue: '99999.99', minimumValue: '0', digitGroupSeparator: '', decimalPlacesOverride: '2'}
            if(obj.className.match(/\bnegative\b/)) {
                options.minimumValue = '-99999.99';
            }
            new AutoNumeric(obj, options);

        });
    }
    add_moneymasks(parent);

    if(moneymask_observer == null) {
        moneymask_observer = new MutationObserver(function (mutations) {
            mutations.forEach(function (mutation) {
                if(mutation.type != 'childList')
                    return;
                add_moneymasks($(mutation.addedNodes));
            });
        });
        moneymask_observer.observe(document.body, {
            attributes: false,
            childList: true,
            characterData: false,
            subtree: true
        });
    }
}
`

..and then:

`$(document).ready(function () {
    add_moneymasks();
});`

**Comment by AlexandreBonneau** [comment]
@benmehlman for information:

-  `decimalPlacesOverride` does not exist anymore since `v2` (see the doc [here](https://github.com/autoNumeric/autoNumeric/blob/next/doc/HowToUpgradeToV4.md#configuration)). You should either use the defaut number of decimal places which is `2`, or force it with `decimalPlaces`.
- To check if a given element is managed by AutoNumeric already, you can use the more expressive `AutoNumeric.isManagedByAutoNumeric('.mySelector > input')` (cf. the [doc](https://github.com/autoNumeric/autoNumeric/#static-methods)).
- Are your inputs in a form element? If so, you could use `AutoNumeric.multiple({ rootElement: formElement, exclude : [hiddenElement, tokenElement] }, { options });` to initialize all those in one call (excluding the elements you don't want to initialize).

About the main issue, since I want to keep the result of `new AutoNumeric` and `AutoNumeric.multiple()` predictable (ie. respectively returning a single element and an array of element(s)), I imagine it could be useful to allow `AutoNumeric.multiple()` to update the settings/value of all the already-initialized AutoNumeric elements.
However, to preserve the current behavior, that would need to complexify the function call to add a new parameter `doNotReInitialize`. The function signature being already complex, I'm not sure this is the right way to go.

Only you two posted here, so until I get more push from users to implement this, the subject will stay open.

**Comment by benmehlman** [comment]
Thanks, I changed to the `decimalPlaces` option.  I am going to play around with it.. but the reason I am doing them with an .each is because I do have to check each one first to make sure they haven't been initialized already.. if so, I have to skip the element.. else, I will have the doubling behavior reported in this issue.  I discovered this at first in a situation where an input was within a hidden div, and this hidden div was later opened as the contents of a jQuery dialog.  It resulted in double initialization due to the observer being triggered.  That is one example.  But there are other places in my code where I could be concerned about double initialization, for example tables where each row contains inputs and rows are dynamically added or removed, or where I am using drag and drop, there is a good number of cases in which the copying or moving of elements could trigger duplicate initialization.  Checking each time prevents the issue with confidence.  I don't love it, but I can't change it.
