### ISSUE TITLE
Valid wheel events with a `deltaY` equal to zero are wrongly ignored and an error is thrown

### ISSUE THREAD

**Issue by HolmstN** [autoNumeric/autoNumeric#641]
### Current behavior
On certain device touchpads (using a Dell Precision 5520 at the moment), when scrolling vertically on a field, the wheelEvent will occur several times and on one of the occurrences, the `wheelEvent.deltaY` value is 0.  

This causes the following error to be thrown:

`The event passed as a parameter is not a valid wheel event, 'wheel' given.`

### Expected behavior
When a touchpad scroll occurs, this error should not occur.

### Steps to reproduce the problem
1. Use autoNumeric version `v4.1.0`
2. Chrome v74, Windows 10
3. Create autoNumeric input
4. Scroll on specific touchpad eg Dell Precision 5520
5. Note the error thrown

### Proposed Step to Fix
Appears this is caused by AutoNumericHelper in following lines:

```js
static isWheelUpEvent(wheelEvent) {
        if (!wheelEvent.deltaY) {
            this.throwError(`The event passed as a parameter is not a valid wheel event, '${wheelEvent.type}' given.`);
        }

        return wheelEvent.deltaY < 0;
    }

    /**
     * Return `true` if the given event is a wheeldown event
     *
     * @param {WheelEvent} wheelEvent
     * @returns {boolean}
     */
    static isWheelDownEvent(wheelEvent) {
        if (!wheelEvent.deltaY) {
            this.throwError(`The event passed as a parameter is not a valid wheel event, '${wheelEvent.type}' given.`);
        }

        return wheelEvent.deltaY > 0;
    }
```

Seems fix would be to check `wheelEvent.hasOwnProperty('deltaY')`, but I can't seem to determine why this deltaY check was put into place originally.  Would this cause other problems?  Simpler choice is to add a first check `if === 0`

If a hasOwnProperty check is all that is needed, I can create a PR.

**Comment by AlexandreBonneau** [comment]
Well, I'm not entirely sure but I think when I added that feature I encountered some bugs with the `wheel` events sometime not returning any `deltaY` property.
I cannot remember which browser or how I found that though.

However, with very high resolution mouse/touchpad, it seems `deltaY` can be equal to `0`.
I'll need to fix the code where I assumed only positive or negative values could be used (for instance the `AutoNumericHelper.throwError(`The event is not a 'wheel' event.`);` lines).

I first need to find the time to fix how the dependency upgrade broke the automated tests ;)

**Comment by marcdagatan** [comment]
Experiencing the same problem:
`Uncaught Error: The event passed as a parameter is not a valid wheel event, 'wheel' given.`

### Versions:
autonumeric version `4.5.10`
using autonumeric through -> react-numeric version `1.0.0`

Machines used:
1)
MBP early-2015, MacOS Mojave `10.14.6`
Chrome Version `79.0.3945.130`

2)
Acer Swift 3, Windows 10
Chrome Version `79.0.3945.130`

### Steps to reproduce:
Create a react component, use it as any input.
 
```js
// using react

import React from 'react';
import { ReactNumeric } from 'react-numeric';

export default ({ onChange }) => (
  <ReactNumeric emptyInputBehavior="null" onChange={(e, value) => onChange(value)} />
);
```

The error is coming from:

```js
// starts from line 793 of AutoNumericHelper.min.js

/**
 * Return `true` if the given event is a wheelup event
 *
 * @param {WheelEvent} wheelEvent
 * @returns {boolean}
 */
static isWheelUpEvent(wheelEvent) {
    if (!wheelEvent.deltaY) {
        this.throwError(`The event passed as a parameter is not a valid wheel event, '${wheelEvent.type}' given.`);
    }

    return wheelEvent.deltaY < 0;
}
```

I find the error occurs when you use a trackpad. when you use a mouse with its wheel, it doesn't have this problem.

Using the trackpad, when you scroll up, and mistakenly veer to the left or right while scrolling, it shows this error.
Likewise, when you scroll left or right, it throws this error.
When scrolling left/right, it gives you a `deltaY: -0`. I guess this is where the problem really comes from.
`!-0` yields you `true` which triggers the `this.throwError`.
Also, with @HolmstN suggestion, you can't use `wheelEvent.hasOwnProperty('deltaY')` because the wheelEvent is a hollow object which would return `.hasOwnProperty('deltaY')` to `false`.

I suggest to check the event type, and/or if the value is undefined instead.
```js
// this.isUndefinedOrNullOrEmpty is within the same class object, line 65

// somewhere in the class object, before line 799:

static isWheelEvent(event) {
  return event instanceof WheelEvent;
}

// line 799
static isWheelUpEvent(wheelEvent) {
        if (!this.isWheelEvent(wheelEvent) || this.isUndefinedOrNullOrEmpty(wheelEvent.deltaY)) {
            this.throwError(`The event passed as a parameter is not a valid wheel event, '${wheelEvent.type}' given.`);
        }

        return wheelEvent.deltaY < 0;
    }

// line 813
static isWheelDownEvent(wheelEvent) {
        if (!this.isWheelEvent(wheelEvent) || this.isUndefinedOrNullOrEmpty(wheelEvent.deltaY)) {
            this.throwError(`The event passed as a parameter is not a valid wheel event, '${wheelEvent.type}' given.`);
        }

        return wheelEvent.deltaY > 0;
    }
```

I can do a PR if someone thinks this would solve this problem, or if it won't break any other tests.
