### ISSUE TITLE
Field gets empty on mouse hover

### ISSUE THREAD

**Issue by rmazarei** [autoNumeric/autoNumeric#645]
Hi.
I have a field (total) that automatically fills based on 2 other fields (e.g. unit_price and unit_numbers).
I have wrote a JS function that will fire on "focusout" (on second field) and fill the "total" field.
But when I hover mouse on the total field, its value disappears.

**Comment by ducman** [comment]
How are you setting the value on the "total" field? Are you using the autoNumeric methods?

**Comment by rmazarei** [comment]
$("#area").on('focusout', function(){
                let pricePerMeter = $("#price_per_meter").val().replace(/,/g,"");
                let priceTotal = addComma($(this).val() * pricePerMeter);

                console.log("Price Per Meter: " + pricePerMeter);
                console.log('Price Total:' + priceTotal);
                $("#price_total").val(priceTotal);
                new AutoNumeric('#price_total', 'integer');
            });

**Comment by AlexandreBonneau** [comment]
This cannot work correctly since you are initializing a new AutoNumeric element on every `focusout` event.
The way to proceed is to first initialized your inputs, then and only then add the wanted behavior on various events.

For instance in your case, you could do something like this (also, pure JS is now better than jQuery):
```
// First initialize your variables and references
const pricePerMeter = new AutoNumeric('#price_per_meter');
const area = new AutoNumeric('#area');
const priceTotal = new AutoNumeric('#price_total', 'integer');

// Then add the logic
area.node().addEventListener('focusout', () => {
    priceTotal.set(pricePerMeter.getNumber() * area.getNumber());
});
```

Since this is not an issue with AutoNumeric, I'll close this and invite you to join the gitter chan if you still have any questions.
