### ISSUE TITLE
Caret position is incorrectly set when the `currencySymbol` in prefix position contains the first value entered

### ISSUE THREAD

**Issue by shrpne** [autoNumeric/autoNumeric#647]
### Current behavior
Set `currencySymbol` option to contain digit on the end. E.g. "a1 "
Write this digit in the input. E.g. "12"
Get wrong value. "121"

### Expected behavior
Value should not be wrong :)

### Steps to reproduce the problem
1. Use autoNumeric version `4.5.4`
2. Any browser (latest chrome firefox and safari tested)
3. On the `OSX` operating system (I believe it is not OS specific)
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, { currencySymbol: 'a1 ' });
```
5. Write value with this digit in the input, e.g. "12". Get wrong value "121".

### Link to live example
https://codepen.io/anon/pen/bPzpLR

**Comment by AlexandreBonneau** [comment]
well, on one hand this is obviously a bug, but on the other hand is there any currency symbols with numbers in it? ;)

**Comment by shrpne** [comment]
I'm using it for crypto coins and in my case, yes:)

**Comment by AlexandreBonneau** [comment]
I updated the title to reflect that the bug was specific when the `currencySymbol` was in the prefix position.
Then when user entered a number, in our case `1`, then the generated regex that calculates where to set the caret after the formatting is done stumbled upon the `1` character in the `currencySymbol`.

This is fixed in `v4.5.9` !
