### ISSUE TITLE
The value [] being set falls outside of the minimumValue [] and maximumValue [] range set for this element

### ISSUE THREAD

**Issue by serginnios** [autoNumeric/autoNumeric#664]
Steps to reproduce the problem
1. Use autoNumeric version `4.5.10`
2. In the browser `Chrome` open http://autonumeric.org/configurator
3. Set configuration option:  maximumValue: "10"
4. Paste any value into input which is greater than maximum (10).

![image](https://user-images.githubusercontent.com/5511895/69432957-5f3ca000-0d43-11ea-927b-72174aa40816.png)

**Comment by AlexandreBonneau** [comment]
I fail to see why this is a bug, could please explain what bothers you here?

**Comment by serginnios** [comment]
It doesn't affect user experience but in my opinion it shouldn't throw the error, in the same way as when you try to enter the value not from [min; max] range.

**Comment by AlexandreBonneau** [comment]
As a user, when you paste something in an element, and see nothing happens, you must have a way to know why it failed.
This error will be hidden for most of the users, and will be used by devs mainly. It can even be caught and shown differently to the user.

The error messages will be kept, since pasting in AutoNumeric offers a wide range of behaviors, and that would help debug things.

Thanks for taking the time to share your point of view on that matter.
