### ISSUE TITLE
when i submit 1 but autonumeric view 100

### ISSUE THREAD

**Issue by whitedevil0303** [autoNumeric/autoNumeric#667]
I inspect with mozilla inspector
`<td class="nomor" value="1,00">100</td>`

sorry english not my mother language

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by joepetrakovich** [comment]
I'm having the same issue I believe.

This was working in a prior version but doesn't work in the latest version.  The below code will now display 100.00% when it used to display 1.00%.   I'm not sure when it changed because I hadn't upgraded the library at all between March and December of last year.  But if I swap in the minified version that we used from March (attached) it works as expected.  I wish I had included the version number :/  I tried recreating in codepen with the version 4.5.4 but it didn't do it.

[autonumeric-we-got-in-march-2019.zip](https://github.com/autoNumeric/autoNumeric/files/4172984/autonumeric-we-got-in-march-2019.zip)

```
const anElement = new AutoNumeric('input', AutoNumeric.getPredefinedOptions().percentageUS2decPos);

var textbox = AutoNumeric.getAutoNumericElement("input");

textbox.set(1);
```

**Comment by joepetrakovich** [comment]
I'm trying to find an older library that recreates it but I can't.  I think it's odd that typing '1' will make it 1.00% but if you call `set(1)` it makes it 100.00%.  Was that always the intent?

**Comment by AlexandreBonneau** [comment]
This is the expected behavior.
`100%` is equal to `1`, `50%` is equal to `0.5` and so on.
Since you are using the predefined `AutoNumeric.getPredefinedOptions().percentageUS2decPos` option, you (unwillingly apparently ;p) are using the `rawValueDivisor` option so that any number you enter will be divided by `100` on blur.

If you want your previous behavior, you could just define the option by yourself, omitting the `rawValueDivisor` one, for instance :
```js
const anElement = new AutoNumeric('input', 0.5, {
	currencySymbol : AutoNumeric.options.currencySymbol.none,
	suffixText : AutoNumeric.options.suffixText.percentage,
	wheelStep : 0.01,
});
```
(see the [live example](https://codepen.io/AnotherLinuxUser/pen/ExjKNRY?editors=1010))
