### ISSUE TITLE
Accept %-character

### ISSUE THREAD

**Issue by mbaas2** [autoNumeric/autoNumeric#671]
I want to define a field for numeric input - with an optional **%**-character, The idea is that users may enter "0.5" or "50%". I only found `suffixText` which would add it permanently - and obviously that is not appropriate for an input like `0.5`. 
This is more something like `ignoreChars`, I think - except that this isn't implemented (yet). Is there another way to make it possible for a field to enter "%" (w/o it affecting the numeric value)?

**Comment by AlexandreBonneau** [comment]
You could use `showOnlyNumbersOnFocus` in combination with the `divisorWhenUnfocused` option to multiply by 100 on blur, so that if your user enters `0.5`, then it would show `50%` on blur.

However we will not complexify AutoNumeric to detect if a value is in the [0;1] range ; you can use `minimumValue` and `maximumValue` for this.
