### ISSUE TITLE
Format all inputs with same class don´t work

### ISSUE THREAD

**Issue by marcowick** [autoNumeric/autoNumeric#686]
I use AutoNumeric.js to format decimal inputs different. My issue is, that not all elements with same class will be formated.

```js
<td><input type='text' name='price_pos1' placeholder="" value="" class='form-control price'></td>
<td><input type='text' name='price_pos2' placeholder="" value="" class='form-control price'></td>

jQuery( document ).ready(function( $ ) {
        new AutoNumeric('.price', {
        decimalCharacter: ",",
        digitGroupSeparator: "." 
    }); 
}); 
```

In the second step i need to calculate the total of each price (table row) and need to fetch the value with:

`    var price = parseFloat(row.find(".price").val());`

Here the AutoNumeric generated value of 1.000 will be converted to 1,00

Complete function:
```js
      (function() {
        "use strict";
        
        $("#pos_table").on("change", "input", function() {
    
          var row = $(this).closest("tr");
          var qty = parseFloat(row.find(".qty").val());
          var price = parseFloat(row.find(".price").val());
          var discount = parseFloat(row.find(".discount").val());
          var whole = qty * price;
            if (discount >= '0') {
                var whole = qty * price - (discount*price/100);
            }else if( $(discount).val()  == '' ) {
                var whole = qty * price;
            }else{
                var whole = qty * price;
            }
          row.find(".whole").val(isNaN(whole.toFixed(2)) ? "" : whole.toFixed(2).replace(/\./g, ','));
        });
      })();
```

Thanks

**Comment by AlexandreBonneau** [comment]
Using `new AutoNumeric()` will always only initialize the very first element it find with the selector.
Since you want to initialize multiple elements, you should use [the AutoNumeric.multiple()](https://github.com/autoNumeric/autoNumeric#initialize-multiple-autonumeric-objects-at-once) function.

That was you are sure to get an array of the initialized elements, that you'll be able to access later to get the values, instead of having to search for those elements again with `find()`.
