### ISSUE TITLE
How to work only with integer value

### ISSUE THREAD

**Issue by PetroGromovo** [autoNumeric/autoNumeric#689]
Hi, 
Which options have I to set in autonumeric@4.1.0 to work only with integer value, 
  without decimal?

Thanks in advance!

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

I would recommend using the `v4.6.*` from `next`, which is pretty stable.
In order to only allows interger values, you only need to set the `decimalPlaces` options to `0`.
