### ISSUE TITLE
Trailing comma, spacing, and incorrect parentheses causes build issues in an application

### ISSUE THREAD

**Issue by cambronjay** [autoNumeric/autoNumeric#700]
### Current behavior
<Please describe here what faulty behavior you are experiencing>
Trailing comma causes build issues

### Expected behavior
No Trailing comma should exist in  math.max

### Steps to reproduce the problem
This code block in the AutoNumeric.js file has a trailing comma after the last additionalDecimalPlacesRawValue variable as bolded below
settings.decimalPlacesRawValue = Math.max(Math.max(settings.decimalPlacesShownOnBlur, settings.decimalPlacesShownOnFocus) +additionalDecimalPlacesRawValue,
            Number(settings.originalDecimalPlacesRawValue) + **additionalDecimalPlacesRawValue,**
        );

**Comment by cambronjay** [comment]
Also there appears to be a bad spacing in the same code block. It should be this without space:        settings.decimalPlacesRawValue = Math.max(Math.max(settings.decimalPlacesShownOnBlur, settings.decimalPlacesShownOnFocus) + additionalDecimalPlacesRawValue, Number(settings.originalDecimalPlacesRawValue) + additionalDecimalPlacesRawValue);

**Comment by cambronjay** [comment]
Essentially wherever settings.decimalPlacesRawValue or currentSettings.originalDecimalPlacesRawValue is used with Math.max there is a trailing comma and there is an issue with missing parentheses to make the order of operations more clear.

**Comment by AlexandreBonneau** [comment]
Trailing commas are valid in function parameters since [ECMAScript 2017](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas).
The autoNumeric eslint configuration uses the [comma-dangle](https://eslint.org/docs/rules/comma-dangle) option accordingly.

If your build is failing, it means your build process does not correctly manage ECMAScript.

All in all, trailing commas, spacing and parentheses are always checked by eslint on build (and during edition via my IDE), so an error there is highly unlikely. I would suggest you give eslint a try (with that [configuration file](https://github.com/autoNumeric/autoNumeric/blob/next/.eslintrc.js); it helps quite a lot.
