### ISSUE TITLE
Mouse leaving is executing the change event in jquery

### ISSUE THREAD

**Issue by Fantablup** [autoNumeric/autoNumeric#723]
### Current behavior
After changing the value and pressing tab on the input field, it is ok. But when the mouse cursor is leaving the input, it fire the change event.
Pressing enter after changing the value and then mouse leaving  works good.
### Expected behavior
It should not fire the change event when mouse is leaving the input.

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.1.0>`
2. In the browser `<Chrome|Firefox>` version `<96.0.4664.45>`
3. On the `<windows 10>` operating system

I had to remove the addeventlistener creation for the mouseleave event in Autonumeric.js.

Thanks for a great plugin.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

I cannot reproduce the bug using that [codepen](https://codepen.io/AnotherLinuxUser/pen/jOGqNBE?editors=1010) with Firefox under Linux. Would that be a windows-only bug?
Perhaps use the latest `4.6.0` version, instead of the old `4.1.0`?

**Comment by Fantablup** [comment]
> Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it. Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?
> 
> I cannot reproduce the bug using that [codepen](https://codepen.io/AnotherLinuxUser/pen/jOGqNBE?editors=1010) with Firefox under Linux. Would that be a windows-only bug? Perhaps use the latest `4.6.0` version, instead of the old `4.1.0`?

Of course :)
[4.1.0 version](https://codepen.io/fantablup/pen/dyVMPgR)
It also fires the change twice on the tab press.

I tried the newest version you suggested, and the bug is gone.
Thanks Alexandre :)
