### ISSUE TITLE
Source has vanished from CDN server, just so you know

### ISSUE THREAD

**Issue by applemad** [autoNumeric/autoNumeric#732]
I have been using your brilliant script for a while now, all of a sudden our page is breaking and the console error is as follows, just thought you should know.

[Error] Failed to load resource: the server responded with a status of 404 () (autoNumeric.min.js.map, line 0)

https://cdn.jsdelivr.net/npm/autoNumeric.min.js.map

**Comment by applemad** [comment]
This was the code I had in my page

<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.1.0"></script>

I have also tried changing it to the latest version:

<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.5.4"></script>

and even tried hosting it locally and it still fails, really strange ..

**Comment by applemad** [comment]
![Screenshot 2022-01-25 at 12 34 13](https://user-images.githubusercontent.com/230327/150977908-39fd21d3-5592-41bb-9be9-d643b187b765.png)

**Comment by applemad** [comment]
Ok weirdly if you use this instead doesn't error, so I'm assuming differences of some kind in either the way its served or in the source on the server itself, as this version looks like an even later version, 4.6.0 on this CDN

<script src="https://unpkg.com/autonumeric"></script>

**Comment by colinj** [comment]
@applemad The reason you are getting the above error (actually everyone will get this error!) is because the `autoNumeric.min.js` file has a reference to the `autoNumeric.min.js.map` (source map) file on its very last line.

```js
//# sourceMappingURL=autoNumeric.min.js.map
```
The browser will try to load the source map file but since it can't find it, you will get the 404 error.  The source map is only useful if you are debugging the autoNumeric code. So you can safely ignore the 404 error.

If it bothers you, you can host the `autoNumeric.min.js` on your local server and remove the last line. Removing the `sourceMappingURL` reference will fix your problem.

**Comment by mhombach** [comment]
@applemad can you please mark this issue as solved? :)
