### ISSUE TITLE
get value from specific input

### ISSUE THREAD

**Issue by donny26utama** [autoNumeric/autoNumeric#755]
```
<input type="text" id="input-1" class="input-auto-numeric">
<input type="text" id="input-2" class="input-auto-numeric">
new AutoNumeric.multiple(".input-auto-numeric");
```

how to get unformatted value from input-1 ??

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

That said, you can access the unformatted value from `input-1` using:
```js
let yourValue = AutoNumeric.getAutoNumericElement('#input-1').getNumericString();
// Be sure to check if the html element is loaded and exist before doing that
```

The better way would be to save a reference to the generated AutoNumeric elements array when using `new AutoNumeric.multiple()`  (see the [doc](https://docs.autonumeric.org/Documentation/initialization/#initialize-multiple-autonumeric-objects-at-once)), so that you can then access the object directly, using:
```js
let ANelements = new AutoNumeric.multiple(".input-auto-numeric");
let yourValue = ANelements[0].getNumericString();
```
