### ISSUE TITLE
Heavy bug with german number formatting

### ISSUE THREAD

**Issue by dqdrt** [autoNumeric/autoNumeric#756]
### Current behavior
German numbers with on grouping/thousands dot will be handled on page-load (or ajax-replace) as english numbers
so 1.000 gets 1.0 (one thousand is converted to one)
900.000 gets 900 
(only if there are no decimal digits)

### Expected behavior
German numbers between 1.000 und 999.999 should not be changed

### Steps to reproduce the problem
Save and open following HTML:

```
<html>
   <head>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/autonumeric/4.6.0/autoNumeric.js"></script>
      <script>
         window.addEventListener("load", (event) => {
            new AutoNumeric("input", {
               currencySymbol: "",
               decimalCharacter: ",",
               digitGroupSeparator: ".",
               decimalPlaces: 2
            });
         });
      </script>
   </head>
   <body>
      <input type="text" value="12.345" />value=12.345 - the german 12.345,00 but without decimal places<br />
      <input type="text" value="1.234.567"/>value=1.234.567 - the german 1.234.567,00 but without decimal places<br />
   </body>
</html>
```

https://pastebin.com/BdgYVacY

### Fix
<Also, when creating an extract of your problem, you are likely to find the cause of it, and fix it yourself, :tada: ;)>

The Problem is in autoNumeric.js (4.6.0) line 10389 in the "_toNumericValue" function.

The first IF for "normal" (english-styled) numbers also miss-matches for german integers between 1.000 and 999.999.
My fix was to check the actual decimalCharacter by changing the original
if (_AutoNumericHelper__WEBPACK_IMPORTED_MODULE_0__["default"].isNumber(Number(value))) {
to
if (settings.decimalCharacter == this.getDefaultConfig().decimalCharacter && _AutoNumericHelper__WEBPACK_IMPORTED_MODULE_0__["default"].isNumber(Number(value))) {

(found no static access to _AutoNumeric__WEBPACK_IMPORTED_MODULE_0__["default"].options.decimalCharacter.dot)

### Another question:
Is there a "hidden" (i haven't found it) function to add the decimal digits directly while typing, not afterwards on blur?
So when i type "1" in an empty field it gets automatically to "1.00" (in english-format), with cursor staying after "1"?

**Comment by AlexandreBonneau** [comment]
Here is [the link](https://codepen.io/AnotherLinuxUser/pen/eYLEyRq) to the related live code example to try to reproduce the aforementioned problem.

AutoNumeric does try to parse any *javascript-formatted* Number passed as the 'default' value.
AutoNumeric does not try to unformat the default attribute value, so using `12.345`, it's correctly interpreted as the decimal number `12.345`.

As you can see in the code, the docs for `_toNumericValue()` states:
```
Convert the `value` parameter that can either be :
- a real number,
- a number represented in the scientific notation (i.e. -123.4567e-6)
- a string representing a real number, or
- a string representing a localized number (with specific group separators and decimal character),
...to a string representing a real 'javascript' number (i.e. '1234' or '1234.567').

This function returns `NaN` if such conversion fails.
```

All in all, the `default` attribute value should always be used with a Javascript Number, not with a formatted one.

This is a feature, not a bug :)

**Comment by blutorange** [comment]
Just my 2 cents. I think this needs to be more clearly stated in the documentation.

The reason why  I think this is such a surprising behavior is that it goes against a normal flow of filling out forms and reopening a form with the submitted data. E.g. a simple application where the user can fill out a form partially, save the form by submitting the form to the server, and continue editing the form later.

* User opens an HTML page with a form, enters a number.
* The formatted number gets submitted when the form is submitted to a server. As autonumeric doesn't store the unformatted numbre in the input field, but the formatted number.
* The server render the form with the current data (`<input value="123.456">`) and sends it to the user's browsers

So from a roundtrip to the server the value is lost.  And it's tricky to even notice this is an issue since it sometimes works and only happens in certain circumstances you might not realize before you get bug reports from your users.

The workarounds I know of to restore a previously submitted formatted number are either to 

* (a) just write the raw value back to the input field after initialization
* (b) to manually use the `unformat` function to retrieve the unformatted value first. But that doesn't really work since the autonumeric constructor accepts `CallbackOptions`, while the `unformat` function only accepts `Options`.
