### ISSUE TITLE
Autonumeric unformatOnSubmit doesn't reformatAfterSubmit

### ISSUE THREAD

**Issue by gap777** [autoNumeric/autoNumeric#769]
### Current behavior
AN will convert a formatted string to a numeric string before the form is submitted, ensuring that the form payload contains the raw value. However, it will not reformat the input value *after* the form data is generated. On pages where the form is present and not driving a redirect, that will make the AN field show its raw value.

### Expected behavior
AN would reformat the field after the form is submitted.

### Steps to reproduce the problem
1. Use autoNumeric version `4.8.1`
2. In the browser `Chrome` version `Version 111.0.5563.146 (Official Build) (arm64)`
3. On the `MacOS` operating system, version `13.3.1 (a)`
4. Create an autonumeric in a form, with `unformatOnSubmit` option; submit the form. See that the field is showing the raw value.

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
[<Providing a live example of your problem that reproduce what you are experiencing usually means we'll be able to fix your issue *much more quickly* than if you don't.>](https://codepen.io/gap777/pen/poxLrax?editors=1011)
Enter a value into the first input (contained by the form). See AN formatting the result. Submit the form. See the raw value in the field until you hover over it.

### Solution

Call `reformat` on each AN managed field after the form data payload is generated.

### Context

Search form with filters

The top-half of a page is a search form. The user enters various filter values, some of which are numeric and formatted with AN. The user hits submit, which needs to contain the raw, unformatted values for the server to use. The server responds with a Hotwire response (HTML over the wire) containing the search results which are (thanks to turbo-rails and turbo-streams) injected into the DOM below the search form. The search form is still present, but shows the raw numeric values.

**Comment by AlexandreBonneau** [comment]
If I understood you correctly the question here is not if `unformatOnSubmit` do unformat on submit (because it does), but why you are using it in the first place.

If you want to send unformatted form values to your server, then you should take a look at the ~10 [specific form methods](https://docs.autonumeric.org/Documentation/instantiated%20methods/#submit-the-form-values) to do that.

**Comment by gap777** [comment]
@AlexandreBonneau Thank you for thinking about this... I think the tension here may be that we're trying to build a system that is not relying upon custom Javascript, but instead uses as much of the standard web actions as possible. In this case, we're relying upon "normal" form submit actions.

I think what you're saying is, "Dont do that"... intercept a form submit event, and submit it ourselves using our own JS logic, wherein we call one of those 10 formatting methods to get the data in the format we want. 

Is that right?

**Comment by AlexandreBonneau** [comment]
I wouldn't be so bold to tell you what to do or not do :)

It's just that you are wanting `unformatOnSubmit` to also do a reformat after having sent the data to the server, and that would be a very niche use case to implement since this can be achieved with one of existing the `formSubmit*()` functions AutoNumeric provides, in a leaner and cleaner way since then you won't even have to unformat anything for a brief moment.

Since you want to do something specific when submitting your form, it means you need a way to tell your components (here your AutoNumeric fields) to do something before, and that means overriding the classic `submit()` function to use your own indeed.

**Comment by louiswdavis** [comment]
I'm having this same issue but simply because if the form errors, the value that's returned and shown in the input is the raw value and not the formatted one, and the formatting doesn't take place until I hover over the input
